### PR TITLE
Prepare 0.5 dev

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

**Comment by jost-s** [comment]
Are we going straight to 0.4.0, no 0.4.0-rc.0?

**Comment by ThetaSinner** [comment]
This is the 0.5 branch now. I have to convince `develop` that it branched from 0.4 after 0.4 was released... I don't like it but that's how this works

**Comment by ThetaSinner** [comment]
The 0.4 release candidate will be produced from `develop-0.4`

**Comment by jost-s** [comment]
:bulb:

**Review by jost-s — APPROVED** [review]

**Pull request merged**
