### PR TITLE
Make run_n and generate functions of hc_sandbox public

### PR DESCRIPTION
**Pull request by matthme**
### Summary
I use the `generate` and `run_n` functions in `holochain_cli_launch` to start sandbox conductors. Instead of having to copy over those functions I would like to import them if there is nothing speaking against making them public.

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by maackle — APPROVED** [review]
Seems OK! Yeah, more surface area means more change of breaking changes, but I guess this closely mirrors the public interface of the CLI anyway.

**Comment by maackle** [comment]
@steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by steveeJ** [comment]
> @steveeJ how near-term? Should we merge this into a branch to run CI on so we can get it in, or is a fix coming soon enough?

i can't justify prioritizing it over the DWeb work so probably not until then. seems reasonable to just push it to a branch in our repo.

**Comment by matthme** [comment]
I'm replacing this with #2271 which is not from a fork.

**Pull request closed without merging**
