### PR TITLE
Update Holochain version in Holonix for 0_3_rc

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by matthme** [comment]
@hra holonix_update 0_3_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/9353702735)

**Comment by c12i** [comment]
@hra holonix_update 0_3_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/9354701140)

**Comment by c12i** [comment]
@hra holonix_update 0_3_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/9354834282)

**Review by ThetaSinner — APPROVED** [review]

**Pull request merged**
