### PR TITLE
Prepare for 0.4 dev releases

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOGs updated with appropriate info

### CODE REVIEW

**Comment by ThetaSinner** [comment]
Rather ugly change. The automation expects a previous version to exist and bases its next decision on that. So even though we haven't released 0.3.0, we need to convince the repo that we have and then ask it to start doing dev releases... I think

**Comment by ThetaSinner** [comment]
Also switching from `beta-dev` to `dev`, which I think we agreed to a long time ago but wanted to wait for the next minor version to action it

**Review by jost-s — APPROVED** [review]
LGTM too

**Review by jost-s — APPROVED** [review]

**Comment by ThetaSinner** [comment]
You're good, I'd asked for core-dev :)

**Comment by ThetaSinner** [comment]
I've just run a simulated next release. It's going to fail due to a bug in the release automation but it does do the correct bump... So this PR is correct and I think we should merge it. Separately I need to take a look at why the release automation doesn't bump self-dependencies consistently...

**Comment by ThetaSinner** [comment]
Hmm, it runs the release checks on the branch... So the thing I thought would break on `develop` has broken here. Well that's good feedback but super unhelpful. I'll have to get that working tomorrow so that we can merge this before the next automated release.

**Comment by jost-s** [comment]
How about not merging the two PRs and carry on after the automated release tomorrow on 0.3.0? Then you're not under pressure with the automated release.

**Comment by ThetaSinner** [comment]
That'd be quite the nasty rebase unfortunately because the release will update the readmes. I'll figure it out :)

**Comment by ThetaSinner** [comment]
There is a release-automation bug but it's one we already know about causing trouble again... -> https://github.com/holochain/holochain/issues/3789

**Comment by ThetaSinner** [comment]
Actually, I already tried to fix it, but there was another bug in the way that I have now also fixed -> https://github.com/holochain/holochain/pull/2622

**Pull request merged**
