### PR TITLE
Update launcher input for weekly

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by matthme — APPROVED** [review]

**Review by steveej — APPROVED** [review]

**Comment by ThetaSinner** [comment]
This doesn't work, and doesn't build - please do not merge :)

**Comment by ThetaSinner** [comment]
It now runs, just the build to sort out

**Comment by ThetaSinner** [comment]
Oh the version flag the tests are using is actually gone... Monday problem :)

**Review by jost-s — APPROVED** [review]

**Review by steveej — APPROVED** [review]

**Comment by matthme** [comment]
> Oh the version flag the tests are using is actually gone... Monday problem :)

Yes and I actually have no clue why that is. It's since I updated from structopt to clap... The version command is supposed to work out of the box but for some reason it doesn't.

**Comment by ThetaSinner** [comment]
@matthme I believe this struct https://github.com/holochain/launcher/blob/develop/crates/hc_launch/src-tauri/src/cli.rs#L24 is missing the line

```rust
#[command(author, version, about, long_about = None)]
```

From the clap docs https://docs.rs/clap/latest/clap/_derive/_tutorial/chapter_0/index.html

If that works I'm happy to roll back the test change I've made on here

**Comment by matthme** [comment]
Indeed, thanks :) I'm actually thinking about adding a custom version number/name there now that indicates the holochain minor version. It's quite a mess otherwise to distinguish different versions of hc-launch regarding holochian compatibility. Unfortunately that doesn't solve the problem when publishing to crates.io but it's better than nothing.

**Pull request merged**
