### PR TITLE
hdk3 doc

### PR DESCRIPTION
**Pull request by ddd-mtl**
Please provide function signature and return type documentation for hdk3 macros so we can know how to use them properly.

### CODE REVIEW

**Review by maackle — APPROVED** [review]
@ddd-mtl we could merge this now, but then we'd lose track of your request to better document hdk functions, which is a good idea. Could you open an issue with this request so we can better track it?

We eventually want to move away from macros for every hdk function, and convert them to proper functions, which will not only give proper type info, but will be a good opportunity for more documentation.

**Comment by ddd-mtl** [comment]
@maackle Yes, no need to merge this. Just wanted to show an example with a diff.
Happy to hear your are intending to switch to proper functions

**Comment by thedavidmeister** [comment]
@ddd-mtl this all got functionized, so i'll close this for now, hope it works better for you :)

**Comment by ddd-mtl** [comment]
Yes, much appreciated, thanks!

**Pull request closed without merging**
