### PR TITLE
Fix GITHUB_TOKEN not available in dispatched workflows

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by steveej — APPROVED** [review]

**Review by steveej — COMMENTED** [review]
i approved as it may be useful to be able to pass a specific token. however this isn't compatible with github actions as is due to:

> secret name `GITHUB_TOKEN` within `workflow_call` can not be used since it would collide with system reserved name

**Comment by steveej** [comment]
which workflow did you see the rate limit hit? it might be missing the passing of `access-token` to nix as done e.g. [here](https://github.com/holochain/holochain/blob/496cb103a3d991f41d6eccb583c970b5a2533b80/.github/workflows/holochain-build-and-test.yml#L83) or [here](https://github.com/holochain/holochain/blob/496cb103a3d991f41d6eccb583c970b5a2533b80/.github/actions/update/action.yml#L41)

**Comment by ThetaSinner** [comment]
Renamed the variable. This isn't about having a specific token though, it's about having any token at all. The secret comes out as an empty string in called workflows unless you pass it.

See this PR where I'm unable to run the tests due to now being allowed to clone Holochain https://github.com/holochain/holochain/pull/2765

**Comment by ThetaSinner** [comment]
The first link to `holochain-build-and-test.yml` is exactly where I had the problem and is what I'm fixing

**Pull request merged**
