### PR TITLE
Update Holochain version in Holonix for 0_3_rc

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by c12i** [comment]
@ThetaSinner do I need to trigger `holonix_update` for this PR?

**Comment by ThetaSinner** [comment]
Not if the commit hash is correct in the updated flake.lock. Are you happy with the current change?

**Comment by c12i** [comment]
Yes, change looks good. We can run this again after `hc launch` is updated

cc @matthme

**Comment by ThetaSinner** [comment]
Super, sounds good

**Comment by matthme** [comment]
And hc launch has just been updated, so good to re-run

**Comment by matthme** [comment]
@hra holonix_update 0_3_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `e 0_3_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/9197851038)

**Comment by matthme** [comment]
@hra flake_update 0_3_rc

**Comment by ThetaSinner** [comment]
@hra holonix_update 0_3_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/9205545152)

**Comment by ThetaSinner** [comment]
There was a mistake in the workflow, fixed now. Does this look like the right launcher version @matthme?

**Comment by matthme** [comment]
Yes, rev looks correct - thanks for fixing!

**Review by ThetaSinner — APPROVED** [review]

**Pull request merged**
