### PR TITLE
format/lint for .sql files

### PR DESCRIPTION
**Pull request by neonphog**
Add sql fmt/lint to holochain_sqlite build.rs

Prints out color diff of formatting changes and note about how to automatically apply them by running `FIX_SQL_FMT=1 cargo build`

sql-fmt-demo

### CODE REVIEW

**Review by maackle — CHANGES_REQUESTED** [review]
I don't think this is an improvement, overall. I like the more uniform indentation this provides for the query-type statements, but I much prefer the old field-aligned spacing on the CREATE TABLE statements. Can you make a case for it?

I already undid a linting attempt [once before](https://github.com/holochain/holochain/commit/993897cb856e3cf597e0a2e22353b26ac1a8fb57)

**Comment by neonphog** [comment]
@maackle 

- Field aligned spacing leads to noisy diffs as it promotes whitespace-only changes to surrounding lines when you have a new field that is too wide for your previous formatting
- The case for standardized formatting is the same case for any type of standardized code formatting / styling: we are currently doing all sorts of weird things with our indenting on deep sql queries. If you have a standard that a machine can apply, the code base is consistent, and the cognitive overhead of reading through the code is lessened.

**Comment by maackle** [comment]
> Field aligned spacing leads to noisy diffs

I don't mind noisy diffs on our schema. Changes to the schema are major, and rare, and deserve some noisy fanfare!

I agree on the rest of the files though. So I won't fight it too hard. Maybe we can bikeshed it real quick next week though.

**Comment by neonphog** [comment]
@maackle - added `no-sql-format` check before performing format check.

**Review by maackle — APPROVED** [review]
Awesome, thanks for finding a compromise

**Pull request merged**
