### PR TITLE
Disable stale workflow for issue closing

### PR DESCRIPTION
**Pull request by ThetaSinner**
### Summary

I think we agreed to do this? We're actively managing issues on GitHub now and our PR list is a sensible length. I think this should now reduce work by not making us touch older issues or put `permanent` on all of them.

### TODO:
- [ ] CHANGELOGs updated with appropriate info
- [ ] All code changes are reflected in docs, including module-level docs

### CODE REVIEW

**Review by neonphog — CHANGES_REQUESTED** [review]
I vote for keeping the PR closing, and just turning off the issue closing.

**Comment by abe-njama** [comment]
> I vote for keeping the PR closing, and just turning off the issue closing.

I concur with this. We exclude issues that can be disabled by the stale workflow.

**Comment by ThetaSinner** [comment]
Tried this. It seems that using `-1` for the times is the only way to disable one or the other - there isn't just a flag. So it'll still check issues but shouldn't do anything with them. I ran the workflow from this branch and it doesn't error, so I guess we'll have to wait and see if the behavior is correct now.

**Review by abe-njama — APPROVED** [review]
Approved based on the feedback [here](https://github.com/holochain/holochain/pull/4150#issuecomment-2265009466) that the workflow will still check Issues but not act on them.

**Review by neonphog — APPROVED** [review]
:+1:

**Pull request merged**
