### PR TITLE
Fix serde renames to actually get snake_case

### PR DESCRIPTION
**Pull request by zdb999**
This pull request fixes the serde rename bugs identified in #420.

### CODE REVIEW

**Comment by Connoropolous** [comment]
This is good... and as a precautionary thing is probably going to cause breaking changes over in holochain-conductor-api
https://github.com/holochain/holochain-conductor-api/blob/develop/src/api/types.ts

**Review by maackle — APPROVED** [review]
Thanks for finding and fixing this @zdb999, and thanks @Connoropolous for looking out for the implications :raised_hands:

**Review by Connoropolous — APPROVED** [review]
I can commit to making some changes to holochain-conductor-api once this gets merged, and this is simple enough, so I'll approve as well 👍

**Comment by Connoropolous** [comment]
I checked out the branch locally and then pushed it to the upstream (this) repo, to trigger CI

**Pull request merged**
