### PR TITLE
Allow clippy::redundant_pattern_matching

### PR DESCRIPTION
**Pull request by maackle**
### Summary

I never met a clippy lint I didn't like...until today. This one just seems harmful. It wants you to use `.is_ok()` instead of `if let Ok(()) = ...`, which would hide information if `()` ever changed to something else.

In general I'm inviting other clippy tweaks to be added. Hopefully this is not a can of worms.

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by neonphog** [comment]
I keep running into [this one](https://github.com/rust-lang/rust-clippy/issues/4971) where my sub-if is checking something totally different. Yes you can combine them to eliminate code branching, but cognitively it's a lot harder to wrap your brain around one layer of divergent logic instead of the hierarchical branches.

- haha, looks like you've run into this too @maackle - https://github.com/holochain/holochain/blob/8de610facd071b1e911de98506d5a9fcc7746523/crates/holochain/src/core/sys_validate.rs#L162-L177

**Review by ThetaSinner — COMMENTED** [review]
It's a shame that these catch some useful things and some things that aren't. The redundant pattern matching will catch matches that error except for one case, that can be converted to `if let`s. Are there few enough wrong cases that it's worth explicitly ignoring the lint for them rather than disabling it globally or is this a regular issue?

**Comment by jost-s** [comment]
> @maackle  It wants you to use .is_ok() instead of if let Ok(()) = ..., which would hide information if () ever changed to something else.

I don't understand the problem, if there's something like
```rust
let a: Result<(), String> = Ok(());
if let Ok(()) = a {
  println!("a ok");
}
```
and then `a` changed to `Result<String, String>`, you'd have to change the `if let` too. It'd be different if it was
```rust
if let Ok(_) = a {
```
but then you don't care about the variant data anyway.

Where is information hidden with `.is_ok()`?

**Comment by maackle** [comment]
@jost-s clippy::style will consider this a redundant match and recommend `if a.is_ok()` instead, purely because the OK type is `()`:

```rust
let a: Result<(), String> = Ok(());
if let Ok(()) = a {
  println!("a ok");
}
```

What I don't like about this is is that if `a` ever became `Result<AnythingElse, String>`, we'd be throwing away the actual value. There's no clippy-sanctioned way to match on a single-valued type to show that we care about what the value is, even though currently the value can only be one thing, acknowledging that one day it might be able to be two or more things.

**Comment by maackle** [comment]
> Are there few enough wrong cases that it's worth explicitly ignoring the lint for them rather than disabling it globally or is this a regular issue?

In my own cost-benefit analysis, a lint that has purely aesthetic benefit is not worth the expense of encouraging a harmful pattern in even a subset of cases. This lint encourages bypassing the type system in some cases, which just seems like a poorly made lint to me.

The point of clippy IMO is to forestall the need for style conversations, so if this PR leads us in the direction of talking a lot more about clippy lints, I'm happy to close this and leave it be, in the name of preventing conversation :)

**Comment by jost-s** [comment]
> What I don't like about this is is that if `a` ever became `Result<AnythingElse, String>`, we'd be throwing away the actual value. There's no clippy-sanctioned way to match on a single-valued type to show that we care about what the value is, even though currently the value can only be one thing, acknowledging that one day it might be able to be two or more things.

Right, I see that. But regardless of whether a can only be one or many things, if we cared about `a` we'd use it inside the match arm, or else if we want to make sure that it's the right type we could do `if a.is_ok() && matches!(a, Ok(AnythingElse))`.

?

**Comment by maackle** [comment]
> f we cared about a we'd use it inside the match arm, or else if we want to make sure that it's the right type we could do if a.is_ok() && matches!(a, Ok(AnythingElse)).

If I cared about `a`, the most succinct way to express it is just `if let Ok(inner) = a`, but that's what clippy::style doesn't like. Your addition of `matches!` is redundant when we already have match statements in Rust, and IMO is further illustration of why this lint is bad.

**Comment by jost-s** [comment]
I see your case. Instead of `if let Ok(Something(Else)) = a` it would have to be `if let Ok(Something(some_value)) = a` because it's the variant data and not the variant data's type that is matched. And if you didn't use `some_value` in the following code, you'd get another lint about unused variables. Hence if you don't use the variable in the match arm, you don't need it, and if you do need it, you cannot forget it.

**Comment by maackle** [comment]
In `Ok(Something(Else)) = a`, imagine that `Else` could have been a unit enum variant that was glob-imported, e.g. `use Foo::{Else, Elf, Shelf}`

**Comment by jost-s** [comment]
> `Else, Elf, Shelf`

😂 

I love this discussion.

The only case is when `Else` is a unit type. Otherwise it has to be `Ok(Something(Else(data)) = a` for when you use `data` and `Ok(Something(Else(_))) = a` for when you don't use the data.

**Comment by jost-s** [comment]
Yes, that's understandable. I still don't think that this single particular case justifies disabling the lint globally and prefer to keep it locally disabled where you see fit.

**Comment by maackle** [comment]
OK, as long as we all continue to use discernment and not blindly do whatever clippy tells us, then I have no concern.

**Pull request closed without merging**
