### PR TITLE
Add active status to InstalledApp for get_app_info calls

### PR DESCRIPTION
**Pull request by zippy**

### CODE REVIEW

**Review by maackle — CHANGES_REQUESTED** [review]
This needs to go a little further. We already differentiate active and inactive apps by storing them in two different maps:

https://github.com/holochain/holochain/blob/207d05e5246085866da888d893be9efa12aaf8ee/crates/holochain/src/conductor/state.rs#L19-L24

This PR isn't updating the `active` field when activating/deactivating an app. But if even it did, this would be needless duplication of state. 

What I think we actually want is a separate struct just for responding to the interface call, like `InstalledAppInfo`, which contains the `active` field. Keep the `active` field out of `InstalledApp`, because that bit of information is already represented by which hashmap it's in, but when constructing the `InstalledAppInfo` during the request, populate the active field based on which map it came from. (see `ConductorState::get_app_info`):

https://github.com/holochain/holochain/blob/207d05e5246085866da888d893be9efa12aaf8ee/crates/holochain/src/conductor/state.rs#L54-L66

So `get_app_info` could return an `InstalledAppInfo` instead of an `InstalledApp`

**Comment by zippy** [comment]
I'm not sure I really understand this point.  `InstalledApp` is already only used as the result of the get_app_info call.  That's all it's for, so why add another type?  Perhaps it's currently poorly named?  I was trying to do something that wouldn't require revving holochain-conductor-api.  I can imagine that if later we want to add other fields that that might make sense.

**Comment by zippy** [comment]
> This PR isn't updating the `active` field when activating/deactivating an app. But if even it did, this would be needless duplication of state.

`InstalledApp` isn't stored.  Only `InstalledAppId`  there's nothing to update.

**Comment by maackle** [comment]
Whoops, I'm getting my wires crossed because in my branches (that I've been working on for two weeks), I *do* store `InstalledApp`. So you're right. Yeah, this is fine. I'll make the change I'm talking about when I merge the two.

**Review by maackle — APPROVED** [review]

**Review by freesig — APPROVED** [review]

**Pull request merged**
