### PR TITLE
Attempting to track down the problem with disabling and re-enabling an app

### PR DESCRIPTION
**Pull request by maackle**
### Summary

We have received a report of zome calls hanging after disabling and re-enabling an app, and then calling into it. I am trying to create a test reproduction but so far have had no luck.

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by Connoropolous** [comment]
@maackle in what context was this disabling / re-enabling issue seen? in the Launcher? Because I am seeing something similar to what this sounds like, and it might be related.

**Comment by Connoropolous** [comment]
The issues seem to relate as well to this issue that I've just logged over here: https://github.com/holochain/launcher/issues/65


dealing with a very large hApp bundle, (75mb) which seems to be getting problematic. 
it manifests like this: 
Screen Shot 2022-09-11 at 10 25 48 AM
and has underlying logs like this: 
```
[2022-09-11T10:08:20.604916-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:20.604[0m [33m WARN[0m holochain::conductor::interface::websocket: Admin socket connection failed: Too many open files (os error 24)
[2022-09-11T10:08:23.815053-07:00] INFO - request; msg=EnableApp { installed_app_id: "hrea_suite" }
[2022-09-11T10:08:53.821094-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821258-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821330-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(Some("unable to open database file: /Users/connor/Library/Application Support/holochain/0.0.156/conductor/dht/dht-uhC0kgN8ZrTQ69XEW4bqhH6v-l4uk9wk5MlrKW1SYbKsP32YP6KFT.sqlite3"))))
[2022-09-11T10:08:53.821395-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=StateQueryError(DatabaseError(DbConnectionPoolError(Error(None))))
[2022-09-11T10:08:53.821454-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821507-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(Some("unable to open database file: /Users/connor/Library/Application Support/holochain/0.0.156/conductor/dht/dht-uhC0kw3V3zFZafKIH7wMQ9Y5NqN0z6fA_Vb_aS44lWx6NE9L-iCMy.sqlite3"))))
[2022-09-11T10:08:53.821562-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821616-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821663-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=StateQueryError(DatabaseError(DbConnectionPoolError(Error(None))))
[2022-09-11T10:08:53.821714-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 17:08:53.821[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821770-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=DatabaseError(DbConnectionPoolError(Error(None)))
[2022-09-11T10:08:53.821975-07:00] INFO - [HOLOCHAIN v0.0.156] [2mSep 11 10:08:53.820[0m [31mERROR[0m holochain::core::queue_consumer: err=StateQueryError(DatabaseError(DbConnectionPoolError(Error(Some("unable to open database file: /Users/connor/Library/Application Support/holochain/0.0.156/conductor/dht/dht-uhC0k-E1VRHSCto-MXLxweN5IiOw01xXWZQnw6Ytl-wDsVTzQ4F4k.sqlite3")))))
```

**Comment by maackle** [comment]
@Connoropolous I haven't tried reproducing in the Launcher itself, this draft PR was about trying to reproduce it purely in terms of the Conductor. Next step would be identifying what's different between the tests I wrote here and what's happening in the Launcher.

Are the problems you report similar to what others have experienced when disabling and reinstalling an app?

I wonder if your issue may have to do with something system-specific like having too low of a `ulimit`?

**Comment by Connoropolous** [comment]
It sounds like others also experienced it in the Launcher? 

"We have received a report of zome calls hanging"
My symptom was also a hanging zome call, yeah, it timed out at 60s which was my set threshold

**Comment by Connoropolous** [comment]
Yeah let me check the ulimit thing

**Comment by maackle** [comment]
Fixed in #1744. The problem was that when performing a kitsune_p2p `leave`, the arc was set to 0 and never grew again.

**Comment by Connoropolous** [comment]
oh nice!

**Pull request closed without merging**
