### PR TITLE
Add no-externs feature

### PR DESCRIPTION
**Pull request by freesig**
### Summary
- Adds the ability to enable the feature flag `no-externs` on any zome to disable all exported functions. This is useful for importing a zome into another zome as a rust dependency without getting linker symbol collisions. If the feature flag `no-externs` is enabled on a zome then all exports will be disabled. The functions will still exist though and if they are not marked `pub` will given unused warnings. To fix this, make the functions `pub`.

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by freesig** [comment]
I can't get the build script to pass because it uses `--workspace` which seems to enable a feature flag in any crate enables it within the workspace.

**Comment by Connoropolous** [comment]
hey @freesig 
I've been thinking a lot about this. 

here's what I'm noticing and thinking about... 

The problem with the fact of the HDK abstracting away the host/guest wasm interface from developers is that they don't really have any idea what's going on under the hood, and are encouraged not to think about or understand WASM super well. 

If a developer has one zome, they will never have to use this, and never face a problem. 
But if a developer adds one coordinator zome which depends on two integrity zomes, which should be a common enough scenario, here's what they're going to first run up against when they try: 

```
  = note: "rust-lld" "-flavor" "wasm" "--rsp-quoting=posix" "--export" "__num_link_types" "--export" "__num_link_types" "--export" "__allocate" "--export" "__deallocate" "--export=__heap_base" "--export=__data_end" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--fatal-warnings" "--no-demangle" "--no-entry" "--export-dynamic" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/hc_zome_indexing_integrity_resource_specification.hc_zome_indexing_integrity_resource_specification.26c5fa0c-cgu.0.rcgu.o" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/hc_zome_indexing_integrity_resource_specification.440h0n6ja9yv251z.rcgu.o" "-L" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps" "-L" "/Users/connor/code/clients/hrea/hREA/target/release/deps" "-L" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libhdk_semantic_indexes_core-cb20b3399f2000a3.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libhdi-cce8d2280dd304b7.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libholochain_wasmer_guest-d487592bf2cf4fac.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libholochain_wasmer_common-f38da7f492c864ea.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libholochain_integrity_types-36e7b4a069ff4aa8.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libtracing-3595c35378fc41dd.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/liblog-3aca9d13ec0a7dda.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libcfg_if-6d0bc25e58490298.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libpin_project_lite-ff1cd4f51002dc59.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libtracing_core-955f79f47b2c5d9c.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libsubtle-8240b6022e1cba4b.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libkitsune_p2p_timestamp-b2c035b5523ddf7f.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libchrono-fbfd505713875ef2.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libtime-90b19a6685cf3ee8.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libholo_hash-e93740e74bdbcbf1.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libblake2b_simd-a13d69561f41f3c4.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libconstant_time_eq-6fca4c8e2e781b06.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libarrayvec-46305eea78530f2f.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libarrayref-8d14686c5ea098b8.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libbase64-fc0fd80aaf07d285.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libkitsune_p2p_dht_arc-606a16aeaade21b6.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libinterval-eacef1d7d69e8862.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libgcollections-a403f7049fc8bf44.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libtrilean-cdbd98809541417c.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libbit_set-7f3cbc8b8c1c196e.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libbit_vec-afedb82e85497e2a.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libnum_integer-0499a6995706dc28.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libholochain_serialized_bytes-ffc594392be909e6.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libserde_transcode-e42050039d810bab.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libserde_bytes-1b790fca91e1a62a.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libthiserror-79e8baff7af48a75.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/librmp_serde-04d1d84552a55a5e.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/librmp-7593438100fb132a.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libbyteorder-3c174e81cbdd1c00.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libnum_traits-840e949c1632ec9a.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libserde_json-c49393d11e192fcf.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libryu-90767e4b1977e540.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libitoa-bb1c09d5acc1c4b4.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libindexmap-471298db2b71bae8.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libhashbrown-2b162aaa87e09bcb.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libahash-7fe991a28e93c72d.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libonce_cell-0a78a8ef529da4ab.rlib" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libserde-5d5b50639c88a030.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd-19abd9397d5e8ed8.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libpanic_abort-5e68841ce68d774e.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libdlmalloc-39dad79c8bdd5316.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/librustc_demangle-6cba0086bbe401ce.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libstd_detect-64c383fd6f8b31e4.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libhashbrown-a1c1b3157dba97b8.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libminiz_oxide-db95b33a9f26855b.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libadler-34b84f702a67af1b.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/librustc_std_workspace_alloc-36fe6ac37b492ca5.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libunwind-d012d584eaca78c7.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libcfg_if-b90300485f849bea.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/liblibc-48a47a0453843221.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/liballoc-cf810f7d6872b95a.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/librustc_std_workspace_core-737aaa0870c60d85.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libcore-82cf5df82026c764.rlib" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/libcompiler_builtins-ab4bc17cc5d80617.rlib" "-L" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib" "-L" "/Users/connor/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-unknown-unknown/lib/self-contained" "-o" "/Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/hc_zome_indexing_integrity_resource_specification.wasm" "--gc-sections" "--no-entry" "-O3"
  = note: rust-lld: error: duplicate symbol: __num_link_types
          >>> defined in /Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/hc_zome_indexing_integrity_resource_specification.hc_zome_indexing_integrity_resource_specification.26c5fa0c-cgu.0.rcgu.o
          >>> defined in /Users/connor/code/clients/hrea/hREA/target/wasm32-unknown-unknown/release/deps/libhdk_semantic_indexes_core-cb20b3399f2000a3.rlib(hdk_semantic_indexes_core-cb20b3399f2000a3.hdk_semantic_indexes_core.33465fc6-cgu.2.rcgu.o)


error: could not compile `hc_zome_indexing_integrity_resource_specification` due to previous error
```

they are not going to have any clue what to do, why this is happening, or how to fix this, or design their code properly. 

They won't have ever heard of __num_link_types and have no idea what it does, or what it's about. 

In addition, I just want to mention that `skip_hdk_extern` and `skip_no_mangle` are still going to be useful to some devs for advanced use cases, so I hope you'll keep those around and announce if you change them.

**Comment by Connoropolous** [comment]
This solution generally works! There should be some documentation somewhere about this too, for sure.

**Review by maackle — APPROVED** [review]

**Comment by freesig** [comment]
Yeh @Connoropolous I'm not sure what to do about that. The hdi is technically a helper library and devs don't need to use it but using low level wasm is not the easiest and can be easy to get wrong.
I also have no idea how to give a better error message as it's a limitation of wasm that we can't detect.
I think the best we can do is document this error and solution but I'm not even sure where to do that. Where would you search for answers? In the hdi docs?

**Comment by Connoropolous** [comment]
There would be two kinds of documentation to make sure of. 
1. Preventative. Put it in on developer.holochain.org if there's any relevant section, definitely put it in the HDI docs and HDK docs, one for configuring your integrity zome, the other for configuring your coordinator zome. 
2. Remedial.  Put the error and error text into a github issue, along with the solution, as that would be where I would search for it.

I'm heading off on a bit of a break till Monday, so don't wait for anything to do with me for this PR now :)

**Review by thedavidmeister — APPROVED** [review]

**Pull request closed without merging**
