### PR TITLE
Release 20211229.084554

### PR DESCRIPTION
**Pull request by jost-s**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by steveeJ — CHANGES_REQUESTED** [review]
please set this PR to target the `main` branch

**Comment by jost-s** [comment]
Ah, that's why the doc says so! 😬

**Review by steveeJ — APPROVED** [review]
looks good to continue the release process :+1: :raised_hands:

**Comment by jost-s** [comment]
Redoing the whole release after fixing issues.

**Pull request closed without merging**
