### PR TITLE
Bump holochain-serialization and holochain-wasmer deps

### PR DESCRIPTION
**Pull request by maackle**
### Summary

It needs to happen for the work I'm doing

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by neonphog — APPROVED** [review]

**Comment by jost-s** [comment]
Yay, at last

**Comment by abe-njama** [comment]
FYI @ThetaSinner

**Comment by steveej** [comment]
this also effectively merged #2829 into develop which was premature IMO as it had some unresolved conversations.

**Comment by maackle** [comment]
It had approvals and no changes requested so I did it. We can always do follow ups. I have too many PRs languishing and collecting merge conflicts, I had to act.

**Pull request merged**
