### PR TITLE
fix(signal-send): log errors instead of returning them

### PR DESCRIPTION
**Pull request by jost-s**
* fix: clippy unneeded mut

* fix(signal): log send error but do not return to caller

* docs(app): add NetworkInfo response link

* test(signal): add signal send test

* docs(changelog): update with fix

* docs(admin-api): mention app interface persistence

* clippy does not like a single match any more =(

* give test more descriptive name

* clippy hammers it in, no single match statements

* move note about app interface persistence higher up

* let others understand signal send error

* trace signal send error as info

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [x] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by jost-s** [comment]
@ThetaSinner Please clarify the procedure, should I set the semver increment modes in the changelogs as part of this PR or in a separate one? And why do I even need to set it just to merge something to develop? Is it so that the develop branch is always ready for release?

**Comment by ThetaSinner** [comment]
@jost-s yes you'll want to bump in a separate PR because you'll only need to do it for the actual release, it's already set right for a beta-rc release. The problem here is the CI checks the semver mode, so you need to make a change in the CI and in Nix to get it to accept this PR. I usually do this after a release. You're looking for `--allowed-semver-increment-modes`, and to set them appropriately except for the occurrences in the release-automation tests

**Comment by jost-s** [comment]
Hm, in which changelog does it say beta-dev?

**Comment by ThetaSinner** [comment]
Weird, it looks like ONLY in the `holochain` crate. These aren't supposed to be out of sync

**Comment by ThetaSinner** [comment]
Actually this might be my problem, my IDE is struggling to keep up and isn't reloading files properly when I switch branch. On github.com the file has the right content. Never mind!

**Pull request merged**
