### PR TITLE
Bump libmdns if addrs

### PR DESCRIPTION
**Pull request by neonphog**
Arg... looks like our CI doesn't run properly from forks @steveeJ 

Opening new PR to get https://github.com/holochain/holochain/pull/1925 merged.

### CODE REVIEW

**Comment by neonphog** [comment]
@steveeJ - Something's not right here, could you take a look when you have a moment?

**Comment by steveeJ** [comment]
> @steveeJ - Something's not right here, could you take a look when you have a moment?

this means that a lockfile isn't up to date; practically speaking that `cargo generate-lockfile --offline` produces a non-zero `git diff`. this is an issue in the build pipeline because it relies on a two step process of vendoring the deps according to the lockfile, and then running the build offline against the vendored deps.

**Comment by steveeJ** [comment]
the other errors are mysterious cachix push errors that are actually no-ops because they seem to happen on cached builds, and i've already asked domenkozar about them.

**Comment by neonphog** [comment]
@steveeJ 

> this means that a lockfile isn't up to date; practically speaking that `cargo generate-lockfile --offline` produces a non-zero `git diff`.

So, to be clear, we, as devs, have to remember to run `cargo generate-lockfile --offline` before committing, even though we have a lockfile that is technically capable of running cargo tests locally?

**Comment by neonphog** [comment]
@steveeJ - I just got the same error, even though I regenerated the Cargo.lock with your command

**Comment by steveeJ** [comment]
@neonphog the error occurs when building the wasm_workspace (with `--manifest-path=crates/test_utils/wasm/wasm_workspace/Cargo.toml`) which has its own lockfile at _crates/test_utils/wasm/wasm_workspace/Cargo.lock _. i've noticed it a lot of times in the past that this lockfile didn't get updated and was only updated at release time. i wonder how we can make this effort-less or at least at least reduce the effort on the devs side. a pre-commit hook maybe?

**Comment by neonphog** [comment]
Now I'm getting this:

```
error: build of '/nix/store/h2bmcf004jj7kwdjxsk31bkwqbsj9glq-holochain-tests-wasm-test-workspace.drv' on 'ssh-ng://builder@167.235.13.208' failed: builder for '/nix/store/h2bmcf004jj7kwdjxsk31bkwqbsj9glq-holochain-tests-wasm-test-workspace.drv' failed with exit code 101;
       last 10 log lines:
       > error: failed to select a version for the requirement `parking_lot_core = "^0.9.0"` (locked to 0.9.7)
       > candidate versions found which didn't match: 0.9.6, 0.8.6, 0.7.3, ...
       > location searched: directory source `/nix/store/jpqi4n6rvgm0x0mmx3bsi81y90imsi50-vendor-cargo-deps/c19b7c6f923b580ac259164a89f2577984ad5ab09ee9d583b888f934adbbe8d0` (which is replacing registry `crates-io`)
       > required by package `parking_lot v0.12.1`
```

**Comment by neonphog** [comment]
@steveeJ 

> a pre-commit hook maybe?

Or even just a simple command to run that would update everything needed...

**Comment by steveeJ** [comment]
i pushed a commit applying a fix according to one of [crane's FAQ entries](https://github.com/ipetkov/crane/blob/cb0c042a274cf531e80567dcff720f321e03eb63/docs/faq/workspace-not-at-source-root.md#cargo-workspace-root-cargotoml-is-not-at-the-root-of-the-derivations-source).

**Review by steveeJ — APPROVED** [review]

**Comment by neonphog** [comment]
Thanks @steveeJ !

**Pull request merged**
