### PR TITLE
refactor(cargo): move some common deps into workspace

### PR DESCRIPTION
**Pull request by steveej**
### Summary

split off #2676 

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by ThetaSinner — APPROVED** [review]
This looks good!

I still think we should get the `release-automation` updated and get some tests that demonstrate the right things get released when their deps get updated in the workspace before we go any further with extracting dependencies.

**Comment by steveej** [comment]
> demonstrate the right things get released when their deps get updated in the workspace before we go any further with extracting dependencies.

do you mean that crates get detected as changed and subsequently released if a workspace dependency they use is updated but not their direct source code?

**Comment by ThetaSinner** [comment]
I mean the opposite, there is no link between the workspace dependency being updated and the crate needing to be released. The crate source code changing I would be surprised if that wasn't working because that's what we rely on for detecting what to release isn't it?

**Comment by steveej** [comment]
> I mean the opposite

i described the intended functionality not the implemented one, so i believe we agree on that :wink:

**Pull request merged**
