### PR TITLE
Verify crates independently without crate2nix

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by steveej** [comment]
i'd like to see something that rules out false positives, i.e. something that actually demonstrates a crate failing when built separately from the workspace. i've not put in the effort to create such a test persistently, but whenever i worked on this part i put together and quick and dirty one to verify it.

**Comment by steveej** [comment]
to be clear i'm not requesting such a test. i'm satisfied if someone does the due diligence for a quick local change and test. let me know if you're up for it otherwise i'll do it.

**Review by steveej — COMMENTED** [review]
see comments i made before this review :wink:

**Comment by ThetaSinner** [comment]
I think this does what you're asking for? https://github.com/holochain/holochain/pull/3188

**Review by steveej — APPROVED** [review]
> @steveej I think this does what you're asking for? #3188

yes, thanks! that's enough to convince me that this works as expected.

**Review by jost-s — APPROVED** [review]

**Pull request closed without merging**
