### PR TITLE
reveal two function cap grant issue via test case

### PR DESCRIPTION
**Pull request by Connoropolous**
shows the issue found in #418 and https://github.com/holochain/holochain-conductor-api/pull/22

the issue is described in #418 and the linked issue

The problem can be seen in the failed CI run for the first commit on the branch:
https://app.circleci.com/pipelines/github/holochain/holochain/3433/workflows/289ad2d6-1d4e-4bf3-b6ad-7bbbe9bc7029/jobs/4120

```
Holochain detected database corruption.

Corrupt module: CasBufUsedSync::get
Expected hash: [88, 36, 81, 118, 189, 254, 45, 205, 78, 178, 18, 0, 165, 28, 240, 206, 128, 88, 195, 10, 196, 141, 209, 177, 236, 171, 112, 220, 154, 68, 40, 156, 82, 181, 248, 0]
Actual hash: [96, 229, 64, 180, 4, 189, 208, 199, 21, 158, 117, 235, 134, 209, 126, 39, 121, 219, 128, 181, 25, 235, 138, 107, 68, 231, 84, 211, 156, 133, 31, 157, 110, 223, 24, 173]
Content: CapGrant(ZomeCallCapGrant { tag: "", access: Unrestricted, functions: {(ZomeName("capability"), FunctionName("needs_cap_grant")), (ZomeName("capability"), FunctionName("accept_cap_claim"))} })

We are shutting down as a precaution to prevent further corruption.
FATAL PANIC PanicInfo {
    payload: Any,
    message: Some(
        Holochain detected database corruption.
        
        Corrupt module: CasBufUsedSync::get
        Expected hash: [88, 36, 81, 118, 189, 254, 45, 205, 78, 178, 18, 0, 165, 28, 240, 206, 128, 88, 195, 10, 196, 141, 209, 177, 236, 171, 112, 220, 154, 68, 40, 156, 82, 181, 248, 0]
        Actual hash: [96, 229, 64, 180, 4, 189, 208, 199, 21, 158, 117, 235, 134, 209, 126, 39, 121, 219, 128, 181, 25, 235, 138, 107, 68, 231, 84, 211, 156, 133, 31, 157, 110, 223, 24, 173]
        Content: CapGrant(ZomeCallCapGrant { tag: "", access: Unrestricted, functions: {(ZomeName("capability"), FunctionName("needs_cap_grant")), (ZomeName("capability"), FunctionName("accept_cap_claim"))} })
        
        We are shutting down as a precaution to prevent further corruption.,
    ),
    location: Location {
        file: "/rustc/d3fb005a39e62501b8b0b356166e515ae24e2e54/src/libstd/macros.rs",
        line: 16,
        col: 9,
    },
}
```

### CODE REVIEW

**Comment by freesig** [comment]
@Connoropolous If you chuck on the `please-one-approval` or `please-two-approval` labels it helps show which PRs are needing reviews :slightly_smiling_face:

**Comment by Connoropolous** [comment]
Ok!

**Comment by Connoropolous** [comment]
@freesig in case it's not clear, I'm not intending to fix this PR, I was just raising the issue in a reproducible way so that the team can tackle this one

**Comment by freesig** [comment]
I believe this has been fixed now??

**Comment by Connoropolous** [comment]
@freesig I guess I'll try merging develop into this branch and see if it magically goes away?

**Comment by steveeJ** [comment]
> I believe this has been fixed now??

Doesn't look like it's fixed. Here's the error we're getting on CI

```
test core::ribosome::host_fn::capability_grants::wasm_test::ribosome_authorized_call ... 
###HOLOCHAIN_SETUP###
###HOLOCHAIN_SETUP_END###
FATAL PANIC PanicInfo {
    payload: Any { .. },
    message: Some(
        assertion failed: `Ok(ExternIO([192]))` does not match `ZomeCallResponse :: Unauthorized(_, _, _, _)`,
    ),
    location: Location {
        file: "crates/holochain/src/core/ribosome/host_fn/capability_grants.rs",
        line: 142,
        col: 9,
    },
}
thread 'main' panicked at 'assertion failed: `Ok(ExternIO([192]))` does not match `ZomeCallResponse :: Unauthorized(_, _, _, _)`', crates/holochain/src/core/ribosome/host_fn/capability_grants.rs:142:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:435:5
   2: holochain::core::ribosome::host_fn::capability_grants::wasm_test::ribosome_authorized_call::{{closure}}
             at ./src/core/ribosome/host_fn/capability_grants.rs:142:9
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
   4: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:54
   5: tokio::coop::with_budget::{{closure}}
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:106:9
   6: std::thread::local::LocalKey<T>::try_with
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/std/src/thread/local.rs:376:16
   7: std::thread::local::LocalKey<T>::with
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/std/src/thread/local.rs:352:9
   8: tokio::coop::with_budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:99:5
   9: tokio::coop::budget
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/coop.rs:76:5
  10: tokio::park::thread::CachedParkThread::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/park/thread.rs:263:31
  11: tokio::runtime::enter::Enter::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/enter.rs:151:13
  12: tokio::runtime::thread_pool::ThreadPool::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/thread_pool/mod.rs:71:9
  13: tokio::runtime::Runtime::block_on
             at /root/project/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.0/src/runtime/mod.rs:452:43
  14: holochain::core::ribosome::host_fn::capability_grants::wasm_test::ribosome_authorized_call
             at ./src/core/ribosome/host_fn/capability_grants.rs:235:9
  15: holochain::core::ribosome::host_fn::capability_grants::wasm_test::ribosome_authorized_call::{{closure}}
             at ./src/core/ribosome/host_fn/capability_grants.rs:93:11
  16: core::ops::function::FnOnce::call_once
             at /nix/store/gbl01hwswvdzzz8fs5g5k3r8g26hh17f-rust-1.53.0-2021-06-17-53cb7b09b/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  17: core::ops::function::FnOnce::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
FAILED
```

**Review by freesig — APPROVED** [review]

**Comment by freesig** [comment]
I think this should be passing now so we can finally merge it :)

**Comment by Connoropolous** [comment]
just cause I'm confused can you point out why what you changed fixed it?

**Comment by freesig** [comment]
The test that was breaking required the `needs_cap_grant` not have a cap grant because it was testing what happens when there wasn't a cap grant

**Pull request merged**
