### PR TITLE
`SweetConductor::signals`

### PR DESCRIPTION
**Pull request by maackle**
## `SweetConductor::signals()`

This function returns a stream of all Signals ever emitted. It can only be called once, because calling it multiple times would produce mutliple consumers of the same underlying stream, which is probably not what you want for a test.

## Test App Interface

Adds "test" variant of AppInterface, which tests can use without needing to spin up a websocket client.

Since our interfaces naively handle calls from anywhere, and emit signals to all interfaces, there is not much to hook up. As we add more interface granularity, we can hook up the test interfaces accordingly.

Test interfaces are not available outside of `[cfg(any(test, feature = "test_utils"))]`

### CODE REVIEW

**Comment by neonphog** [comment]
> This function returns a stream of all Signals ever emitted.

Technically broadcast channels can "lag" if you don't poll them frequently enough.

**Review by neonphog — APPROVED** [review]
lgtm :+1:

**Review by freesig — APPROVED** [review]
Nice

**Comment by freesig** [comment]
Just a note that broadcast channels can drop messages if the receiver lags behind the sender.

**Comment by maackle** [comment]
Good catch, I bumped the channel size to 1000 for test interfaces

**Pull request merged**
