### PR TITLE
fix(nix/modules/launcher): add wrapGAppsHook

### PR DESCRIPTION
**Pull request by steveeJ**
this fixes an issue where the filechooser doesn't work

### Summary

can be tried out using `nix develop github:holochain/holochain/pr_hc-launch_fix_filechooser#holonix`

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [x] make proper use of [wrapGAppsHooks](https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-hooks)
- [x] @matthme how can we verify the other workarounds (WEBKIT_DISABLE_COMPOSITING_MODE and GIO_MODULE_DIR) are still functionaL?
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by DavHau — APPROVED** [review]

**Comment by DavHau** [comment]
Tests failed first on a missing socket error. Re-ran them and now it's all green

**Comment by steveeJ** [comment]
@DavHau i'm not sure whether or not the wrapGAppsHook clobbers the custom wrap arguments [here](https://github.com/holochain/holochain/pull/1976/files#diff-08df87a4a7a4a95f0b4e7aa36ee7083e657f704c644909a7e8ce20c8c221506cR74-R75). none of our tests cover this code as it's functionality inside the wrapped binary that relies on it, and since the executable is a binary it's difficult to verify statically.

**Comment by DavHau** [comment]
Wrapping something two times shouldn't be an issue, right? We will just end up with two layers of wrapping which is fine.
So I'd say, we go ahead and merge it.

I don't quite understand what makes it hard to test. I guess the custom wrapper has been introduced to fix some breakage. Can't we just test for that breakage?

**Review by matthme — APPROVED** [review]
Approved and tested on my Ubuntu 22.04.

**Pull request merged**
