### PR TITLE
Fix link to HDI in HDK README

### PR DESCRIPTION
**Pull request by dukejones**
### Summary
HDI is its own crate now; update the links in the README in the HDK.

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by jost-s** [comment]
Thanks for your contribution, @dukejones. The intra-doc links are currently working correctly. You can check that on https://docs.rs/hdk/latest/hdk/.

I've tested your submission anyway. In VSCode the link isn't resolved and doesn't work, and when building the docs locally and clicking on the `../hdi` link, I get this
image

Is something not working for you?

**Comment by dukejones** [comment]
@jost-s 
From: https://developer.holochain.org/references/
Links to: https://github.com/holochain/holochain/blob/develop/crates/hdk/README.md

Several links to the HDI point to: https://github.com/holochain/holochain/blob/develop/crates/hdk/hdi

However, HDI is its own crate now. It's not within HDK any more. This link thus no longer works.

Try hitting my version of the page on GitHub, click on the link and see if it works. That's closer to how it will actually be used.
https://github.com/WorldTreeNetwork/holochain/blob/5d9c698d121abd8d84078530f9828342ef01bfab/crates/hdk/README.md

**Comment by jost-s** [comment]
@dukejones Do you mean that people will look up the Holochain docs more likely on Github than on docs.rs?

image
The HDK reference links to docs.rs.

I'd rather change the developer pages than break the Rust intra-doc link. People shouldn't read Rust docs on Github.

Other opinions, @maackle @thedavidmeister, @abe-njama?

**Comment by dukejones** [comment]
Are you suggesting the links in the documentation should link to docs.rs when mentioning the HDI?

**Comment by jost-s** [comment]
Actually the linked Github page called "HDK introductory guide" is just the Rust docs, displayed on Github. I'll remove that, it doesn't belong there and it's useless to display docs.rs pages on Github.

**Comment by jost-s** [comment]
All Github links removed, only links to docs.rs now.

**Pull request closed without merging**
