### PR TITLE
Change signature in comments for recv_remote_signal

### PR DESCRIPTION
**Pull request by tixel**
It is better to use ExternIO instead of SerializedBytes as the type in the signature.
This way you can do more than just forward the signal to the UI.
You can decode the payload and implement logic in the zome if needed.

The same signature is used in elemental-chat: https://github.com/holochain/elemental-chat/blob/develop/zomes/chat/src/lib.rs#L41

### CODE REVIEW

**Comment by Connoropolous** [comment]
@tixel 
yah I noticed things being odd around this as well... 
interesting that you linked to the elemental chat, which I also had to reference myself in order to implement signals in Acorn... 

I also wonder, why does it need to be decoded, then forwarded to the UI? 
https://github.com/holochain/elemental-chat/blob/95cd0038d5fd30d5239576d178d54afa729417c2/zomes/chat/src/lib.rs#L42-L44
```rust
    let sig: SignalPayload = signal.decode()?;
    debug!("Received remote signal {:?}", sig);
    Ok(emit_signal(&sig)?)
```

I guess because it is encoded before it is sent:
https://github.com/holochain/elemental-chat/blob/4f42f30c9ba4e83ba167f588c693cfbb6fb504ef/zomes/chat/src/entries/message/handlers.rs#L255-L257
```
    let input = SignalPayload::Message(signal_message_data);
    let payload = ExternIO::encode(input)?;
    remote_signal(payload, active_chatters)?;
```

But maybe the extra layer of encoding and decoding is unnessary? I can't make sense of it.



There is also this we could add... as documentation around what needs to be done in the `init` callback, at least for now
```rust
    let mut functions: GrantedFunctions = BTreeSet::new();
    functions.insert((zome_info()?.zome_name, "recv_remote_signal".into()));

    create_cap_grant(CapGrantEntry {
        tag: "".into(),
        // empty access converts to unrestricted
        access: ().into(),
        functions,
    })?;
```

**Comment by Connoropolous** [comment]
@guillemcordoba do you have experience to add insight to this ^^ ?

**Comment by guillemcordoba** [comment]
Not really, to me it just seems like the hdk function needs signature needs to change to be similar to that of emit_signal, doing that encoding at the hdk layer. @thedavidmeister am I wrong?

**Comment by freesig** [comment]
Ping @thedavidmeister I don't know enough about this to figure it out. Also any reason why this PR is on a comment??

**Comment by Connoropolous** [comment]
@freesig I did a bad thing and expanded the scope of the conversation / convoluted this. The original PR was straightforward and to the point. 
There is just an out of date / innacurate / misleading comment, and this seems to fix that. 
At least if we look at a functioning app, like elemental chat, it makes it clear: 
https://github.com/holochain/elemental-chat/blob/develop/zomes/chat/src/lib.rs#L41

**Comment by tixel** [comment]
> Ping @thedavidmeister I don't know enough about this to figure it out. Also any reason why this PR is on a comment??

The code comment explains what function you have to implement when you want to receive remote signals. 
I tells you to use:
recv_remote_signal(signal: SerializedBytes)
which works, if the only thing you do in that method is forwarding the signal to the UI.

It creates typing problems when you want to do some extra logic, like inspecting the signal.

In ElementalChat they use a different signature
recv_remote_signal(signal: ExternIO) 
https://github.com/holochain/elemental-chat/blob/develop/zomes/chat/src/lib.rs#L41
this signature works too and has no typing problems.

The comment is currently (if I'm not mistaken) the only documentation on remote signals. 
Already few people had to figure this out. So changing the comment would help others.

**Review by thedavidmeister — APPROVED** [review]
yeah don't get me in the way of a simple comment fix :)

**Pull request closed without merging**
