### PR TITLE
Fix gossip initiate

### PR DESCRIPTION
**Pull request by freesig**
### TODO:
- [x] CHANGELOG(s) updated with appropriate info

### CODE REVIEW

**Comment by Connoropolous** [comment]
what was the observable effect this was having @freesig ?

**Comment by zippy** [comment]
@Connoropolous this is the thing that was making long-lived DHTs fail to sync.  I've been running a DHT now all afternoon and it's been working like a charm.

**Comment by Connoropolous** [comment]
oh ok gotcha.

**Comment by freesig** [comment]
Sort of, it's more that stale agent info was being initiated with and never timing out so the gossip would just stall. The bug has to do with sale agent info which just happens to appear when you run the dht for a long time.

**Review by zippy — APPROVED** [review]
From a testing point of view I approve this release, haven't read the code though and will leave that to others.

**Review by neonphog — APPROVED** [review]

**Pull request merged**
