### PR TITLE
gossip arc clamping option for sandbox

### PR DESCRIPTION
**Pull request by Connoropolous**
### Summary
needed to test this out so I added this option

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by Connoropolous** [comment]
I would have done but I don’t know how to set the tuning params in the file. Is there a documented example of that?

**Comment by ThetaSinner** [comment]
I'm not sure about documentation but the config from the launcher is a useful reference. Looking at my local install I have

```
network:
  transport_pool:
    - type: proxy
      sub_transport:
        type: quic
        bind_to: ~
        override_host: ~
        override_port: ~
      proxy_config:
        type: remote_proxy_client
        proxy_url: "kitsune-proxy://<an-id>/kitsune-quic/h/137.184.142.208/p/5788/--"
  bootstrap_service: "https://bootstrap.holo.host/"
  tuning_params:
    gossip_strategy: sharded-gossip
    gossip_loop_iteration_delay_ms: "1000"
    gossip_outbound_target_mbps: "100"
    gossip_inbound_target_mbps: "100"
    gossip_historic_outbound_target_mbps: "100"
    gossip_historic_inbound_target_mbps: "100"
    gossip_burst_ratio: "100"
    gossip_peer_on_success_next_gossip_delay_ms: "60000"
    gossip_peer_on_error_next_gossip_delay_ms: "300000"
    gossip_agent_info_update_interval_ms: "300000"
    gossip_redundancy_target: "100"
    gossip_max_batch_size: "1000000"
    gossip_dynamic_arcs: "true"
    gossip_single_storage_arc_per_space: "false"
    default_rpc_single_timeout_ms: "60000"
    default_rpc_multi_remote_agent_count: "3"
    default_rpc_multi_remote_request_grace_ms: "3000"
    agent_info_expires_after_ms: "1200000"
    tls_in_mem_session_storage: "512"
    proxy_keepalive_ms: "120000"
    proxy_to_expire_ms: "300000"
    concurrent_limit_per_thread: "4096"
    tx2_quic_max_idle_timeout_ms: "60000"
    tx2_pool_max_connection_count: "4096"
    tx2_channel_count_per_connection: "2"
    tx2_implicit_timeout_ms: "60000"
    tx2_initial_connect_retry_delay_ms: "200"
    tx5_max_send_bytes: "16777216"
    tx5_max_recv_bytes: "16777216"
    tx5_max_conn_count: "40"
    tx5_max_conn_init_s: "20"
    danger_tls_keylog: no_keylog
    danger_gossip_recent_threshold_secs: "900"
    disable_publish: "false"
    disable_recent_gossip: "false"
    disable_historical_gossip: "false"
  network_type: quic_bootstrap
chc_namespace: ~
db_sync_strategy: Fast
```

Any new tuning parameters should sit under the `tuning_params` key

**Comment by maackle** [comment]
Yes, let's please not expose these. Kitsune tuning params are not considered part of the public API, they're subject to change at any time, not something we want to ever support. @ThetaSinner's suggestion is what I'd go with (or use your own fork at will!)

**Comment by Connoropolous** [comment]
sure, np

**Pull request closed without merging**
