### PR TITLE
Support custom Header Timestamp, and fix CapGrant serialization/hashing

### LINKED ISSUE #599: Seeing DB corruption in CasBufUsedSync::get, trying to do a CapGrant
Intermittently during Javascript testing of a Zome, I see the following failure while trying to do a CapGrant during the Zome's `fn init( _: () )`:

```
★ thread 'holochain-tokio-thread' panicked at 'Holochain detected database corruption.
★
★ Corrupt module: CasBufUsedSync::get
★ Expected hash: [132, 33, 36, 136, 181, 215, 48, 179, 69, 97, 244, 50, 224, 38, 215, 215, 228, 106, 136, 29, 210, 99, 35, 143, 3, 228, 213, 235, 181, 77, 184, 195, 73, 56, 124, 204, 195, 167, 9]
★ Actual hash: [132, 33, 36, 50, 150, 172, 101, 76, 225, 68, 3, 255, 214, 74, 213, 28, 216, 28, 109, 127, 19, 11, 171, 152, 154, 12, 182, 29, 242, 244, 193, 234, 43, 4, 205, 106, 25, 124, 240]
★ Content: CapGrant(ZomeCallCapGrant { tag: "", access: Unrestricted, functions: {(ZomeName("mutualcredit"), FunctionName("authorize")), (ZomeName("mutualcredit"), FunctionName("transfer_authorized"))} }\
)
★
★ We are shutting down as a precaution to prevent further corruption.', /tmp/nix-build-holochain.drv-1/source/crates/holochain_lmdb/src/buffer/cas/buf_sync.rs:107:9
★ stack backtrace:
★
08:21:42 ^[[32minfo^[[39m:
☯☯☯ {{{CONDUCTOR c0}}}
☯    0: rust_begin_unwind
☯    1: std::panicking::begin_panic_fmt
☯    2: holochain_lmdb::buffer::cas::buf_sync::CasBufUsedSync<C,P>::deserialize_and_hash
☯    3: holochain_lmdb::buffer::
08:21:42 ^[[32minfo^[[39m:
☸☸☸ {{{CONDUCTOR c0}}}
☸ cas::buf_sync::CasBufFreshSync<C,P>::get
☸    4: holochain_state::element_buf::ElementBuf<P>::get_entry
☸    5: holochain_state::source_chain::SourceChain::query
☸    6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
☸    7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
☸    8: std::thread::local::LocalKey<T>::with
☸    9: tokio::runtime::enter::Enter::block_on
☸   10: tokio::runtime::handle::Handle::block_on
☸   11: tokio::runtime::thread_pool::worker::block_in_place
☸   12: holochain::core::ribosome::host_fn::query::query
☸   13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
☸   14: std::panicking::try
☸   15: <FN as wasmer_runtime_core::typed_func::HostFunction<wasmer_runtime_core::typed_func::
08:21:42 ^[[32minfo^[[39m:
☮☮☮ {{{CONDUCTOR c0}}}
☮ ExplicitVmCtx,A,Rets>>::to_raw::wrap
☮   16: <unknown>
☮ note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
☮
08:21:42 [tryorama] ^[[31merror^[[39m: Test error: {
  type: 'error',
  data: {
    type: 'ribosome_error',
    data: 'Wasm error while working with Ribosome: CallError("RuntimeError: \\"Holochain detected database corruption.\\n\\nCorrupt module: CasBufUsedSync::get\\nExpected hash: [132, 33, 36, 136, 181, 21\
5, 48, 179, 69, 97, 244, 50, 224, 38, 215, 215, 228, 106, 136, 29, 210, 99, 35, 143, 3, 228, 213, 235, 181, 77, 184, 195, 73, 56, 124, 204, 195, 167, 9]\\nActual hash: [132, 33, 36, 50, 150, 172, 101, 76\
, 225, 68, 3, 255, 214, 74, 213, 28, 216, 28, 109, 127, 19, 11, 171, 152, 154, 12, 182, 29, 242, 244, 193, 234, 43, 4, 205, 106, 25, 124, 240]\\nContent: CapGrant(ZomeCallCapGrant { tag: \\"\\", access: \
Unrestricted, functions: {(ZomeName(\\"mutualcredit\\"), FunctionName(\\"authorize\\")), (ZomeName(\\"mutualcredit\\"), FunctionName(\\"transfer_authorized\\"))} })\\n\\nWe are shutting down as a precaut\
ion to prevent further corruption.\\"")'
  }
}
```

### PR DESCRIPTION
**Pull request by pjkundert**
Support hdk::prelude::create of Headers with specific Timestamp
    o In order to implement deterministic delta-t based algorithms (eg.
      PID loops, Kalman filters, etc.), it must be possible to specify
      the exact Timestamp that a commit will have.
    o An Option<Timestamp> is added to EntryWithDefId, which is used
      during the Header build process, if supplied.
    o EntryWithDefId::at() and ::new_at() are provided to specify it.
    o A defect in RibosomeError::EntryDefs message was fixed.
    o All other workflows remain the same, with the Header timestamp
      set at commit time.  The source_chain.put method has a new
      Option<Timestamp> argument to carry the data.
    o The Timestamp API has been cleaned up a bit; only From<i64> integer
      conversion supported, but converting from any DateTime<Tz> support
      added.  Also Timezone::epoch() and ::default() added.
    o Test of EntryWithDefId.at() added to wasm_workspace/create_entry
    o Minor cleanup of some Cargo.toml reqwest versions to reduce bloat

This subsumes and will resolve #601 and resolve #599.

Therefore, it changes the CapGrant API to use BTreeSet/BTreeMap instead of HashSet/HashMap, so that
CapGrant entries can be deterministically serialized/deserialized and retain the same commit hash.

The serious problems with validation remain, but seem unrelated to the issues with CapGrant, or adding custom Header Timestamps.

More work should be done on verifying that Header Timestamps are sane, I think, but these problems exist now (arbitrary Header timestamps can already be created by adjusting the system clock around hdk::prelude::create_entry calls), so these improved tests are orthogonal to this feature/improvement.

### CODE REVIEW

**Review by thedavidmeister — APPROVED** [review]
approving, i'd like to hear from @artbrock about allowing wasm code to influence the timestamp of a header

**Comment by pjkundert** [comment]
The concern about Header Timestamps is valid.  As far as I could tell, there is not a lot of validation going on in the construction of the source-chain
- That the timestamp should be monotonic and increasing (we definitely should test for this; are we?)
- That the header timestamp is not too far in the future vs. current time (?)

The "far in the future" test can be defeated by adjusting the system clock outside the holochain system, so we can already arrange to commit Headers with arbitrary future timestamps.  Should they be rejected by the DHT Validators?   The first-level DHT validators may be complicit...  So, I don't know how to test for that reliably.

But, this isn't a problem "added" by this pull...  :)

In my mutualcredit DNA, I'm adding tests to ensure Preauths and Transfers occur within the time bounds specified for the transaction.  But in general, committing a far-future source-chain entry Header just prevents the Agent from committing any "more recent" entries in the future.  I think it might fall on each Zome author to decide whether far future commits are sensible, and disallow them?


This pull is necessary to implement other necessary algorithms, such as Interest and Demurrage which require time-based calculations that *must* have precisely determined bounds in order to recalculate and validate.  The only such precise bounds are the Header commit Timestamp (unless we ship a whole new set of parallel Timestamps in the contents of the Entry).  This seems like the better option.

A future update will be to allow *any* agent to commit a Header on behalf of some other Agent, if we have their Signature.  This implies, of course, that we can commit Headers with pretty much arbitrary Timestamps -- so long as that Agent has signed it.

**Comment by thedavidmeister** [comment]
fwiw there is a discussion about time here - https://github.com/holochain/holochain/blob/develop/crates/hdk/src/time.rs

and if we are adding... or even just exacerbating... any issues, or maybe even improving something, we should maybe review the docs?

**Comment by pjkundert** [comment]
Thanks @thedavidmeister; We aren't making things worse; as stated there, it is already trivial to create arbitrary future Header.timestamp on commit by adjusting the system clock, and the commit *should* already reject a Timestamp in the past -- now we can easily check!  It might even make *sense* for some Zome to commit far-future Header Timestamps (eg. to only allow 1 commit per some long time period), so these far-future tests should be in the Zome validation code, I think.

As for the `sys_time()`, API, in my opinion it should either be a chrono::DateTime<chrono::Utc> or a Timestamp, not a core::time::Duration, but that is a separate pull...

**Comment by artbrock** [comment]
> ...there is not a lot of validation going on in the construction of the source-chain.

There may be more than you realize happening in the combination of sys validation and agent activity peers checking forks and rollbacks.

    - That the timestamp should be monotonic and increasing (we definitely should test for this; are we?)
  
  Yes, this is covered in system validation.

    - That the header timestamp is not too far in the future vs. current time (?)

This **should** be covered in SysValidation too... but not sure it's happening yet.

So... I think people are waiting for me as Product Owner to say whether it's okay to let apps in WASM change the header timestamp.

I definitely have concerns about it. However, it may also be necessary for something like an app to restore source chain backups. (Unless we provide conductor services for that.)

It may be worth a bit more discussion. Why is that you need to change timestamps for this use case?

BTW... I don't consider it so trivial to change your system time when you have multiple apps running (leaving evidence of tampering) or nodes might refuse to connect with you because of incompatible time configuration (recording more evidence of time tampering).

**Comment by pjkundert** [comment]
Hi, @artbrock.   Thanks for taking a look at this.

The one key piece of data that must be defined in order to create "deterministic" commits of Headers is the Timestamp.  If there is no workflow provided that allows specifying the Timestamp (ie. if it is always just computed from the system time at the moment the Header is placed in the DHT), then we can't every reconstruct a source-chain (as you mentioned regarding source-chain backups). 

As for Zomes, this should be a rare event.  We don't even need to publish it as a documented API at this early point, until we get some mileage on it.  As we discussed, I think it needs to be integrated with a workflow that allows *any* agent to publish/broadcast a Header and Entry signed by any *other* agent.  I think it should actually commit it, not just publish it.  As in, it should actually move that Agent's "Top Commit" pointer ahead to the newly published Header, if appropriate.

There are many networking scenarios I can imagine where DHTs are in "disjoint" networks, and the only interface is via some Agent that happens to be connected to both networks, and has access to both DHTs.  For my Mutual Credit implementation, I collect Auth information from each counterparty by a remote Zome "authorize" call.  This includes, of course, the full source-chain including the Header and Signature of some commit (eg. a Preauth or Transfer).

If I happen to be connected (by some weird network plumbing like multiple VPNs) to agents in two DHTs that can't generally each-other -- for example, if I'm in some offline community like a local bazaar, but I happen to have a Starlink I'm using to hit the wider Internet -- I can collect Auth information for commits that have been published by some local Agent in the Bazaar and have hit other Bazaar DHT Validators, but won't be hitting the wider Internet DHT any time soon.  I'd like to be informed if there are any Agents in the bazaar that are trying to double-spend.

To do that, I need to publish their header(s) from the source-chains I've collected, up to the one matching the Agents' current "Top" DHT Header.  Perhaps this occurs automatically, but I don't see how it could -- there are just no routes between the bazaar and the wider Internet, other than my node, which is connected to both by non-routing links.


But, as for this commit -- it adds a very constrained capability to an Agent: the ability to provide the only nondeterministic component of a Header: the Timestamp.  In return, we get the capability to fully reconstruct source-chains from backups.  We also get the capability to attempt to commit Headers in the past (rejected, if out of order with existing "Top" entry) or the future (OK, but it prevents the Agent from committing anything without an artificial Timestamp, until that wallclock time passes).

As for adjusting the clock artificially; if sufficiently determined, an attacker can quite easily make this happen.  We must be able to withstand such Headers being published, of course, and this commit gives us the capability to (at least) write tests for this easily...


As for why I need this, specifically: computing certain types of fees require the knowledge of elapsed delta-t (dt).  We could include another layer of Timestamp in the content of the committed Entries, or utilize the Header.timestamp() -- the fees computed up to and including the Entry+Header encompass exactly the delta-t between the last commit's Header.timestamp() and the current commits Header.timestamp().  Much cleaner, and no need to load and deserialize the Entries, validate the additional Timestamp to compute the dt.

**Comment by thedavidmeister** [comment]
> The one key piece of data that must be defined in order to create "deterministic" commits of Headers is the Timestamp. If there is no workflow provided that allows specifying the Timestamp (ie. if it is always just computed from the system time at the moment the Header is placed in the DHT), then we can't every reconstruct a source-chain (as you mentioned regarding source-chain backups).

we could solve this outside of wasm, or inside of wasm in a dedicated callback that does allow direct manipulation of headers for the express purpose of replaying history

> As for adjusting the clock artificially; if sufficiently determined, an attacker can quite easily make this happen. We must be able to withstand such Headers being published, of course, and this commit gives us the capability to (at least) write tests for this easily...

not sure anyone is saying an attacker is incapable of messing with the system clock, the question for me is just whether exposing this so directly to not-attackers introduces a footgun for happ devs or not

how can this go wrong? how much does it steepen the learning curve for new happ devs?

i get there are benefits to this (which is why i approved it in my review) and it's probably benign if 90% of happ developers are just ignoring it, but i like that we're mentally kicking the tires on this a bit

FWIW i think you can do a lot of the defensive testing against header timestamps that you want with the mocking functionality in develop

turning this around, are there things that happ developers _should_ be doing/testing against that they can't or aren't currently? i would have expected all the timestamp related validation for headers to be standardised and handled by the system validation

**Comment by pjkundert** [comment]
Thanks for the comments, @thedavidmeister, @artbrock .

Construction of source-chain commits should remain as simple as possible for most Zomes, and validation rules should take care of ensuring that commits of invalid state-changes cannot occur.  For example, if multiple simultaneous Zome API calls query the "current" state of the source-chain, and attempt to commit incompatible "new" states.  However, these tests seem to be deferred to the DHT propagation phase; it appears that there *might* be a race condition in the local source-chain update phase -- in other words, where multiple Zome threads could attempt to create local commits, both threads creating Headers that reference the current chain_head(), and then both commit.

This patch now makes these tests for chain_head and sequence validity explicit at the source-chain Header creation phase.  It provides an *optional* (available by importing the `hdk::prelude::builder::HeaderDeterminism` trait) means for specifying the Header `timestamp`, the `prev_header` and the `header_seq` explicitly.

A problem that presently exists (as far as I can determine) is that there is no simple, direct way to ensure that multiple Zome threads can query the current source-chain state, compute a next state and then "atomically" commit it, in such a way that the "other" thread will fail when it finally attempts to commit -- basic Read-Modify-Write atomicity.  This requires each thread to uniquely specify the next  commit, and if successful, prevent the other from committing.

The value of a Mutual Credit ledger is one example.  If multiple Zome threads evaluate the present source-chain to compute a current available Ledger balance, it should not commit unnecessary updates.  Either the DHT Validation methods need to be updated to detect and reject unnecessary updates -- or the Zome function itself can specify eg. the commit's sequence number, and cause the commit attempt to fail, if the source chain has been update during its calculations.

This optional capability is implemented by the `HeaderDeterminism` trait the `Create`, `Update` and `CreateLink` Headers in this pull.  It is not part of the public `hdk::prelude` interface and must be pulled into Zome code explicitly.

We can and should also use it for testing, because I suspect that there are still race conditions in the core source-chain validation and commit code...   Also, this pull allows creation of headers with exactly the same or greater timestamp as a prior header.  This could already occur (subsequent calls to obtain the current time can be identical, if the local clock is being adjusted), so a zero delta-t between Headers should be considered valid.

**Comment by thedavidmeister** [comment]
> Thanks for the comments, @thedavidmeister, @artbrock .
> 
> Construction of source-chain commits should remain as simple as possible for most Zomes, and validation rules should take care of ensuring that commits of invalid state-changes cannot occur. For example, if multiple simultaneous Zome API calls query the "current" state of the source-chain, and attempt to commit incompatible "new" states. However, these tests seem to be deferred to the DHT propagation phase; it appears that there _might_ be a race condition in the local source-chain update phase -- in other words, where multiple Zome threads could attempt to create local commits, both threads creating Headers that reference the current chain_head(), and then both commit.
> 
> This patch now makes these tests for chain_head and sequence validity explicit at the source-chain Header creation phase. It provides an _optional_ (available by importing the `hdk::prelude::builder::HeaderDeterminism` trait) means for specifying the Header `timestamp`, the `prev_header` and the `header_seq` explicitly.
> 
> A problem that presently exists (as far as I can determine) is that there is no simple, direct way to ensure that multiple Zome threads can query the current source-chain state, compute a next state and then "atomically" commit it, in such a way that the "other" thread will fail when it finally attempts to commit -- basic Read-Modify-Write atomicity. This requires each thread to uniquely specify the next commit, and if successful, prevent the other from committing.
> 
> The value of a Mutual Credit ledger is one example. If multiple Zome threads evaluate the present source-chain to compute a current available Ledger balance, it should not commit unnecessary updates. Either the DHT Validation methods need to be updated to detect and reject unnecessary updates -- or the Zome function itself can specify eg. the commit's sequence number, and cause the commit attempt to fail, if the source chain has been update during its calculations.
> 
> This optional capability is implemented by the `HeaderDeterminism` trait, for the `Create`, `Update` and `CreateLink` Headers in this pull. The trait is not part of the public `hdk::prelude` interface, and must be pulled into Zome code explicitly.
> 
> We can and should also use it for testing, because I suspect that there are still race conditions in the core source-chain validation and commit code... Also, this pull allows creation of headers with exactly the same or greater timestamp as a prior header. This could already occur (subsequent calls to obtain the current time can be identical, if the local clock is being adjusted), so a zero delta-t between Headers should be considered valid.

@pjkundert @artbrock

have you got a failing test that shows two headers forking a local chain because that should never happen

how did you determine that headers are not committing atomically?

the validation logic is run for every element locally before it is published and two headers cannot be committed in parallel locally with the same chain seq afaik

**Comment by pjkundert** [comment]
Here is proof @thedavidmeister, I believe, of what I was claiming could happen:

https://github.com/holochain/holochain/commit/5ec47d73654fb9016da30e3dae0c6fbc63e95f14

If multiple `init()` calls ran simultaneously, you could see`HeadMoved` errors.  So, this was "solved" by ensuring inits were run serially.  However, this is *not* the correct solution to this problem.  It only covers up the root cause in this one case, and doesn't prevent the general case.

Any Zome code that follows the pattern:

- Inspect current source-chain state
- Deduce next state
- Commit next state to source-chain

must explicitly handle the case where some *other* thread adjusts the state between Inspect and Commit!  

This could perhaps be handled semi-automatically, perhaps, by remembering the current chain head hash during any Inspect calls (`get...`), and then failing the Commit if it has advanced, forcing the Zome function to restart.  Sort of like ACID databases do.  But -- no side-effects can be allowed!

Therefore, this approach fails when remote Zome calls come into play, because the partially complete Zome call may have changed the state of external parties before failing.

I believe that the only approach is to allow Zome code to:

1. Inspect the source-chain state
2. Deduce the next state, *including the expected header sequence number*
3. Commit next state to source-chain
4. On commit failure, undo (or account for) any remote state-change, and loop back to 1)

**Comment by thedavidmeister** [comment]
@pjkundert does this cover what you're reaching for? https://hackmd.io/TIYnlkJLSiOsSHPQw2_ywA

**Comment by thedavidmeister** [comment]
@pjkundert also i think the expected header seq is baked into the wasm workspace so it already does what you are suggesting in the subconscious, the wasm shouldn't need to be aware of any local concurrency

**Comment by pjkundert** [comment]
I was concerned when I visually inspected the code which assigned the *next* sequence number.  There did not seem to be any "blocking" at that point (that I could see), indicating that multiple threads could assign the same *next* sequence number, and then one would succeed later on when finally committing it to the source chain, and the other one(s) would fail.

This assumption seems to be borne out by maackle's experience, in needing to serialize `init()`.  If your hypothesis was true, then each `init()` would have blocked when allocating the next sequence number, until the prior `init()` thread had succeeded in committing, and would not have thrown the designated error.

I could be wrong.

**Comment by thedavidmeister** [comment]
> I was concerned when I visually inspected the code which assigned the _next_ sequence number. There did not seem to be any "blocking" at that point (that I could see), indicating that multiple threads could assign the same _next_ sequence number, and then one would succeed later on when finally committing it to the source chain, and the other one(s) would fail.
> 
> This assumption seems to be borne out by maackle's experience, in needing to serialize `init()`. If your hypothesis was true, then each `init()` would have blocked when allocating the next sequence number, until the prior `init()` thread had succeeded in committing, and would not have thrown the designated error.
> 
> I could be wrong.

@pjkundert yes, if there are two concurrent writes then one will fail and another will succeed

we don't know what a zome call will do, many zome calls will be read only so we want them to be able to thread

a zome call that writes _should_ fail if the local chain has changed while it was in flight, at least by default

in the future we want to support writes that will attempt to "rebase" on a new chain state if it moves, but this would be opt-in behaviour

why do you think that is the wrong behaviour?

**Pull request closed without merging**
