### PR TITLE
package holochain package & tests via crane; refactor nix version management

### PR DESCRIPTION
**Pull request by DavHau**
### Summary
Refactor the nix code to use nix flakes for version management. (downward compat to old nix clients is established)
This prepares us for potential future steps:
  - merge the 3 repos `holochain` `holochain-nixpkgs` `holonix` into one
  - unify our nix version management to only use one tool and get rid of custom version management scripts
  - get rid of a lot of shell glue code that's currently living inside github workflow yaml files and is hard to debug (we can just nix .#run test-xy)
  - nixify more of the tests, to allow running them locally via a simple `nix run .#...`

Things Done:
  - re-package holochain via crane to split deps into separate drv and also run tests inside a derivation.
  - re-package holochain via `crate2nix` (for experimenting only)
  - ./nix/compat.nix (flake-compat) is used for downward compatibility
  - `nix-shell` still uses the old definitions, not the ones from the flake (keeping it compatible to the current CI).
  - niv isn't used anymore but still kept as CI needs niv add holochain-nixpkgs
  - copied some sh scripts from holonix 

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by DrewMcArthur** [comment]
hey @DavHau, (i'm the author of #1764) not sure how helpful this will be, but i just tried running `nix-shell` in this branch, and copied the output into [this gist](https://gist.github.com/DrewMcArthur/e7db50a52f5166e2493d2ebfa67c3f81) for you.  

I'm running the latest macOS, `12.6.2 (21G320)`, on a `MacBook Pro (Retina, 13-inch, Early 2015)`, 2.7ghz intel i5, 8gb ram, intel graphics.

let me know if i can provide any more information, retry another way, or be helpful in another way.   thanks for your work on this!

**Comment by DavHau** [comment]
@DrewMcArthur Thanks a lot for testing. The problem should be fixed by https://github.com/holochain/holochain-nixpkgs/pull/996
I now updated this branch to reference the new version of `holonix` that includes the fix.

**Comment by DavHau** [comment]
@DrewMcArthur Thanks again for your intense testing and your fixes.
Since this branch here does still have some experimental components, I ported the fixes to develop via https://github.com/holochain/holochain/pull/1777

Could you give it a try again and let me know?
We still have to update holonix to reference the new version of holochain, but you can test the cargo build and test already in the dev shell of the holochain project.

**Comment by DrewMcArthur** [comment]
@DavHau left [this comment](https://github.com/holochain/holochain/pull/1776#pullrequestreview-1253697210) on #1776 - that branch works for me!

**Comment by steveeJ** [comment]
almost all of this, or a version thereof, has been merged in #1863 

thanks for the great work @DavHau and thank you for testing @DrewMcArthur :pray:

**Comment by DrewMcArthur** [comment]
awesome @steveeJ!  and do i understand correctly that holochain.love is a reflection of the current main branch?  i.e. i can test on my macbook with that url now?  or is there a release cycle i need to wait for?

**Pull request closed without merging**
