### PR TITLE
chore(nix): update sources

### PR DESCRIPTION
**Pull request by steveeJ**
### Summary
this was produced by running `./nix/update.sh` in the repo

### TODO:
- [x] set up cachix for circleci to reduce CI time

### CODE REVIEW

**Comment by jost-s** [comment]
Hey @steveeJ, there are only the updated revision numbers here. Do you want me to review those?

**Comment by steveeJ** [comment]
.@jost-s :laughing: 

i think i requested your review to this as part of the out-of-band communication that was going on at the time. i wanted to make you aware of how to update the holonix version in this repo. we use _niv_ here too. we don't have an update job on CI yet for this but i think it'd be appropriate to set on up.

**Comment by jost-s** [comment]
@steveeJ I agree, and it would be nice to go one step further. I just came across this need on a different path.

I want to set up a CI for Tryorama to upgrade and test again current Holochain versions, so it would be great to be able to just update to the latest version using one command.

**Comment by steveeJ** [comment]
@jost-s 

> I want to set up a CI for Tryorama to upgrade and test again current Holochain versions, so it would be great to be able to just update to the latest version using one command.

i messaged you out-of-bands to initiate a conversation around this. i think i can help out but it's not in scope of this PR.

---

@maackle

as this PR came up because our holonix revision was lacking `hn-init`, i want to make you aware that while this updated revision can include `hn-init`, it is disabled by default by the `includeScaffolding = false` default in the _config.nix_

**Review by abe-njama — APPROVED** [review]

**Pull request merged**
