### PR TITLE
DRAFT ONLY: hc database explorer

### PR DESCRIPTION
**Pull request by ThetaSinner**
### Summary

For now this is a very rough draft PR. It adds a basic ability to connect to a database and look at its contents.

The question is, would this be useful to persue? Is it something people would use?

Please don't put too much attention on looking at the code beyond a high-level 'is it using the right access points into the code base' etc. It's very rough at the moment!

##### Current problems

Connecting to a database you don't own is risky. For example, connecting this to the Launcher's conductor upgrades those databases and the Launcher can no longer start. That's definitely not good but unfortunately the entrypoint I'm using doesn't let me scope down to a read-only connection. This really ought to be read-only.

It takes a fair few new packages for `hc` to achieve this. Including this tool by default would increase the size of the binary. I haven't looked yet at how much but I think that's something we would want to consider before going down this route.

##### How to use

Set up with

```shell
cargo install --path . --features db-encryption
cargo install --path . --features db_explorer,db-encryption
```

Run a sandbox, install an app and then

```text
> hc db-explore
$ configure /var/folders/8g/tvqzjrfj4d529fg72xp0g50h0000gp/T/mAekeeCnavso3W12m6O8K/conductor-config.yaml --admin-port 63481
Attempting to load "/var/folders/8g/tvqzjrfj4d529fg72xp0g50h0000gp/T/mAekeeCnavso3W12m6O8K/conductor-config.yaml"
Connecting to the conductor's admin interface
Connecting to admin port 63481
Done
$ list-dna
[DnaHash(uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ)]
$ use authored uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ
$ list-agents uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ
["uhCAkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q", "uhCAkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-"]
$ dump uhCAkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q
all [Record { signed_action: SignedHashed { hashed: HoloHashed { content: Dna(Dna { author: AgentPubKey(uhCAkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q), timestamp: Timestamp(2023-04-05T10:15:20.562229Z), hash: DnaHash(uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ) }), hash: ActionHash(uhCkk9-EXIfzEq8G5MWY3n62xN1lUnWUQhfHCU9n_6V4qjOMzowLF) }, signature: [95, 158, 188, 144, 25, 112, 244, 138, 27, 139, 100, 185, 68, 183, 24, 115, 237, 54, 228, 35, 196, 126, 21, 165, 159, 21, 2, 145, 41, 207, 107, 239, 55, 61, 39, 43, 165, 7, 194, 171, 61, 66, 73, 184, 143, 197, 50, 40, 0, 178, 195, 19, 121, 47, 194, 95, 109, 218, 69, 135, 73, 255, 144, 3] }, entry: NotApplicable }, Record { signed_action: SignedHashed { hashed: HoloHashed { content: AgentValidationPkg(AgentValidationPkg { author: AgentPubKey(uhCAkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q), timestamp: Timestamp(2023-04-05T10:15:20.564669Z), action_seq: 1, prev_action: ActionHash(uhCkk9-EXIfzEq8G5MWY3n62xN1lUnWUQhfHCU9n_6V4qjOMzowLF), membrane_proof: None }), hash: ActionHash(uhCkk_NNxYZJ7hdehqxoRZFCiXTnM5KlWlWOYRQpS1qSbumJLU6u0) }, signature: [11, 203, 59, 191, 4, 93, 127, 238, 233, 63, 154, 186, 210, 221, 191, 72, 4, 212, 80, 208, 158, 136, 143, 43, 26, 254, 78, 226, 178, 151, 235, 8, 10, 223, 78, 182, 39, 178, 120, 23, 91, 174, 27, 206, 12, 40, 248, 63, 171, 54, 110, 157, 238, 210, 253, 173, 245, 27, 3, 138, 169, 133, 174, 4] }, entry: NotApplicable }, Record { signed_action: SignedHashed { hashed: HoloHashed { content: Create(Create { author: AgentPubKey(uhCAkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q), timestamp: Timestamp(2023-04-05T10:15:20.564739Z), action_seq: 2, prev_action: ActionHash(uhCkk_NNxYZJ7hdehqxoRZFCiXTnM5KlWlWOYRQpS1qSbumJLU6u0), entry_type: AgentPubKey, entry_hash: EntryHash(uhCEkE64n582bdmQJXZn3CYZ45bdRPyhoFE32W9ZdT9Xao_A7Qw-Q), weight: EntryRateWeight { bucket_id: 255, units: 0, rate_bytes: 0 } }), hash: ActionHash(uhCkkW-wE-N5HG9tm-zXYeaC0DM7r8JQE9US9he8HLrku_plrw6-p) }, signature: [222, 156, 109, 166, 142, 25, 50, 239, 98, 193, 199, 32, 203, 212, 38, 192, 250, 62, 142, 18, 139, 94, 34, 107, 166, 0, 134, 205, 218, 121, 41, 160, 12, 203, 233, 212, 136, 47, 118, 190, 44, 203, 195, 197, 146, 126, 229, 173, 237, 19, 138, 74, 247, 103, 156, 116, 93, 62, 223, 209, 56, 143, 87, 1] }, entry: NotStored }]
$ dump uhCAkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-
all [Record { signed_action: SignedHashed { hashed: HoloHashed { content: Dna(Dna { author: AgentPubKey(uhCAkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-), timestamp: Timestamp(2023-04-05T10:05:04.729566Z), hash: DnaHash(uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ) }), hash: ActionHash(uhCkkqjNw4_DvHFuwS1gi1Rt__fCJ7cBZgSqTT2QWlUUmrsQBL71h) }, signature: [53, 101, 178, 92, 209, 132, 37, 100, 54, 149, 71, 105, 96, 171, 255, 83, 98, 146, 4, 179, 163, 44, 161, 112, 202, 26, 216, 81, 57, 158, 56, 213, 2, 55, 60, 163, 165, 191, 161, 85, 156, 52, 61, 244, 63, 20, 193, 115, 31, 197, 222, 61, 136, 237, 109, 181, 44, 33, 247, 17, 10, 248, 110, 15] }, entry: NotApplicable }, Record { signed_action: SignedHashed { hashed: HoloHashed { content: AgentValidationPkg(AgentValidationPkg { author: AgentPubKey(uhCAkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-), timestamp: Timestamp(2023-04-05T10:05:04.731515Z), action_seq: 1, prev_action: ActionHash(uhCkkqjNw4_DvHFuwS1gi1Rt__fCJ7cBZgSqTT2QWlUUmrsQBL71h), membrane_proof: None }), hash: ActionHash(uhCkkqiAtFavSyb_Hha54AhAgY5JPx4solktnhkt9fAu5SGe9XQ_d) }, signature: [64, 20, 191, 159, 50, 202, 252, 21, 251, 137, 118, 181, 53, 105, 13, 96, 146, 121, 115, 112, 20, 248, 242, 240, 216, 36, 9, 111, 177, 89, 222, 8, 6, 195, 17, 92, 64, 17, 35, 240, 210, 190, 188, 102, 232, 155, 146, 146, 212, 105, 174, 250, 29, 10, 6, 151, 140, 184, 26, 38, 159, 98, 36, 2] }, entry: NotApplicable }, Record { signed_action: SignedHashed { hashed: HoloHashed { content: Create(Create { author: AgentPubKey(uhCAkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-), timestamp: Timestamp(2023-04-05T10:05:04.731599Z), action_seq: 2, prev_action: ActionHash(uhCkkqiAtFavSyb_Hha54AhAgY5JPx4solktnhkt9fAu5SGe9XQ_d), entry_type: AgentPubKey, entry_hash: EntryHash(uhCEkojuH9IuAoeIW5Au3pXUArJgAxJ8LJJhdjiVVHl9OO3i_DZt-), weight: EntryRateWeight { bucket_id: 255, units: 0, rate_bytes: 0 } }), hash: ActionHash(uhCkkohFwIelCle0NKr5kX1jLvecjmqD2xn2ChA8Fdx7inMI9cgz3) }, signature: [73, 194, 134, 232, 91, 226, 244, 87, 184, 172, 169, 92, 18, 166, 154, 192, 183, 61, 189, 38, 148, 0, 165, 249, 108, 127, 201, 100, 176, 2, 28, 20, 138, 126, 178, 70, 147, 169, 1, 19, 190, 102, 71, 173, 4, 4, 14, 6, 157, 27, 155, 189, 141, 164, 140, 119, 123, 103, 68, 104, 82, 18, 37, 14] }, entry: NotStored }]
```

Check that the database is encrypted and you wouldn't be able to read it otherwise

```text
> sqlite3 /var/folders/8g/tvqzjrfj4d529fg72xp0g50h0000gp/T/mAekeeCnavso3W12m6O8K/authored/authored-uhC0kKKpj6ha7_kvx3tZJNsHf_SraLzhWHbdC1fNJmjFcuEt9TBaJ.sqlite3
SQLite version 3.41.2 2023-03-22 11:56:21
Enter ".help" for usage hints.
sqlite> SELECT name FROM sqlite_schema WHERE type='table' ORDER BY name;
Parse error: file is not a database (26)
sqlite>
```

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by neonphog** [comment]
> It takes a fair few new packages for hc to achieve this. Including this tool by default would increase the size of the binary.

You can make it an external hc subcommand, so it's a separate optional crate that won't increase the size of the hc binary itself.

**Comment by neonphog** [comment]
> Connecting to a database you don't own is risky. For example, connecting this to the Launcher's conductor upgrades those databases and the Launcher can no longer start.

Interesting strategy to use the `Spaces` struct to gain access to the database. I can see how that DRYs out the access calls, while also causing this upgrade problem... Some random off-the-cuff thoughts:

- is this even a problem? most of the time people will have the same hc / launcher versions, right?
- it *probably* wouldn't be too hard to add a `read_only_db` feature to the conductor code that would side-step the upgrade process, and only open read-only connections in the db pool.
- depending on the goals of this utility, it might not actually be that much code to use a direct read-only rusqlite connection for doing selects on the database, and just use holochains structures for parsing the msgpack in the blob fields... but it would require some duplication of the database encryption key logic.

**Comment by neonphog** [comment]
> The question is, would this be useful to persue? Is it something people would use?

I do occasionally wish I could inspect running databases, but only if the friction of using it was less than adding tracing logs in the code at points where I'm debugging things as I've done up to now.

As an alternate, or possibly parallel strategy, I wonder how hard it would be to have a sql generator that would convert all our blob types to text, and if they're messagepack use serde-transcode to turn them into json, and if they're hash types, to convert them into our canonical string reprs... then dump a converted unencrypted sqlite snapshot file that could be viewed through a normal sqlite explorer gui utility.

**Comment by ThetaSinner** [comment]
Thanks for the interesting ideas @neonphog! I've had a read but it's getting late so I'm going to let those absorb and get back to you tomorrow 😄  My initial reaction is that the 'decoder' idea to create a user friendly copy of the database might be the simplest thing to use, especially as it doesn't 'do' anything with the data so the user is free to consume it however suits them. I like that the `spaces` approach gives you back a structured response but I see it very quickly getting into translating CLI input into query options and as soon as you get into links there's not an obvious way to print the output back to a console. Maybe this makes sense as two tools as you hinted at, so an ability to decode but also some way to explore the structure without having to have a working knowledge of the data model (e.g. 'I'm a happ dev and I know what entry types I want and how far back in time I want to go but I don't have a reason to learn how that is actually stored')

Anyway, tomorrow! 😄

**Comment by ThetaSinner** [comment]
Taking longer than I hoped to get back to this! Hopefully there will be some time in the next couple of weeks

**Comment by maackle** [comment]
> I'm a happ dev and I know what entry types I want and how far back in time I want to go but I don't have a reason to learn how that is actually stored

Yes, I want to hold for this use case too. It seems like we should at least give an easy way for devs to ask "what is the content at this hash"? Perhaps even exposing the same functionality as `query` (querying the local chain). It doesn't have to be much more than that.

Indulging in some thoughts about what this could become in the future: Instead of just looking up hashes in local storage, it could do a full cascading network call in the case of sharded networks. Also, imagine hooking this up with IDE/editor support, where you point the plugin to a holochain environment, and every hash in your log file becomes a link that lets you see its content and other info -- and you can keep clicking around to continue exploring, for instance traversing the chain backward just by exploring the `prev_hash` of successive actions, or exploring a link structure by following successive targets.

**Comment by ThetaSinner** [comment]
Too out of date now, to come back to at some point

**Pull request closed without merging**
