### PR TITLE
accept comma-delimited argument for `hc sandbox g -d`

### PR DESCRIPTION
**Pull request by pdaoust**
### Summary

While testing and writing about `hc`, I discovered that the `--directories` argument doesn't actually accept a comma-delimited list; it'll use the whole list as the first directory name and then autogenerate the rest of them.

I built and tested it manually, and it works. But I'd love to learn how to write an automated test for this sort of thing, cuz I might be dipping into `hc`'s codebase a few more times by the time I finish this adventure.

### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [x] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by maackle — APPROVED** [review]
Looks good. As for testing, looks like [we haven't yet figured out how to get `hc` tests to run in CI](https://github.com/holochain/holochain/blob/3c2dda73397e12c8163151ce0f7e3f982a999cb2/crates/hc_sandbox/tests/cli.rs#L54), so that would be a prerequisite

**Comment by matthme** [comment]
seems to fix #1648 :)

**Review by jost-s — APPROVED** [review]
Brilliant! I've tested this too - works.
I wanted to suggest a correction for the help text, but it's not part of the changed code, so I pushed a commit for it.

**Comment by pdaoust** [comment]
Just discovered this PR languishing -- going to merge it as soon as it passes CI.

**Pull request merged**
