### PR TITLE
Update Holochain version in Holonix for 0_3

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by ThetaSinner — APPROVED** [review]

**Comment by matthme** [comment]
I just tested the current hc-launch with holochain 0.3.2 (and lair-keystore 0.4.5) and everything still works fine. One question though before I would approve - is it expected that there is no hash change for lair in the flake.lock even though it was bumped in the flake.nix?

**Comment by ThetaSinner** [comment]
Well spotted, no that's been missed. Thank you!

**Review by matthme — APPROVED** [review]

**Comment by ThetaSinner** [comment]
@hra holonix_update

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `` - [Workflow](https://github.com/holochain/holochain/actions/runs/10185564692)

**Comment by ThetaSinner** [comment]
@hra holonix_update 0_3

**Comment by ThetaSinner** [comment]
That's include the scaffolding update, I think we're good to merge this. Then scaffolding will need to do another update, due to circular update problems :)

**Review by ThetaSinner — APPROVED** [review]

**Pull request merged**
