### PR TITLE
Expose all validation types as public in holochain_integrity_types crate

### PR DESCRIPTION
**Pull request by abe-njama**
Every type that is in these crates is changed to fully public as they are serialized (and therefore public anyway).

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by abe-njama** [comment]
@freesig here are the changes although I focused this on the holochain-integrity-types crate. Are there any other crates where I need to do this as well? Maybe the holochain_deterministic_integrity?

**Review by freesig — APPROVED** [review]
Looks good although you might need to add documentation on the fields now that they are public

**Review by thedavidmeister — APPROVED** [review]
looks good but note this is failing tests and has merge conflicts, so will need to be cleaned up before merge

**Comment by abe-njama** [comment]
> looks good but note this is failing tests and has merge conflicts, so will need to be cleaned up before merge

I've fixed the merge conflicts.

**Pull request merged**
