### PR TITLE
Merge release-20221219.021856 back into develop

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Please double-check the consistency of the CHANGELOG.md files

### CODE REVIEW

**Comment by holochain-release-automation2** [comment]
failure: https://github.com/holochain/holochain/actions/runs/3727841956

this PR was determined to be part of a release due to its branch prefix _release-_.

**Review by jost-s — APPROVED** [review]

**Comment by holochain-release-automation2** [comment]
failure: https://circleci.com/gh/holochain/holochain/40425

this PR was determined to be part of a release due to its branch prefix _release-_.

**Comment by holochain-release-automation2** [comment]
failure: https://circleci.com/gh/holochain/holochain/40445

this PR was determined to be part of a release due to its branch prefix _release-_.

**Comment by holochain-release-automation2** [comment]
failure: https://circleci.com/gh/holochain/holochain/40441

this PR was determined to be part of a release due to its branch prefix _release-_.

**Comment by holochain-release-automation2** [comment]
failure: https://circleci.com/gh/holochain/holochain/40444

this PR was determined to be part of a release due to its branch prefix _release-_.

**Pull request closed without merging**
