### PR TITLE
Update Holochain version in Holonix for 0_3

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by matthme** [comment]
@hra holonix_update 0_3

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3` - [Workflow](https://github.com/holochain/holochain/actions/runs/12144754905)

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3` - [Workflow](https://github.com/holochain/holochain/actions/runs/12144841674)

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3` - [Workflow](https://github.com/holochain/holochain/actions/runs/12144957696)

**Comment by matthme** [comment]
@hra holonix_update 0_3

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_3` - [Workflow](https://github.com/holochain/holochain/actions/runs/12145543719)

**Review by matthme — APPROVED** [review]
Both launcher and scaffolding are at the right commit now.

**Pull request merged**
