### PR TITLE
Update Holochain version in Holonix for 0_4_rc

### PR DESCRIPTION
**Pull request by holochain-release-automation2**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by matthme** [comment]
@hra holonix_update 0_4

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_4` - [Workflow](https://github.com/holochain/holochain/actions/runs/12145047065)

**Comment by matthme** [comment]
@hra holonix_update 0_4

**Comment by matthme** [comment]
@hra holonix_update 0_4_rc

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_4` - [Workflow](https://github.com/holochain/holochain/actions/runs/12145386019)

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_4_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/12145387968)

**Comment by holochain-release-automation2** [comment]
Got it, will try to update inputs for Holonix version `0_4_rc` - [Workflow](https://github.com/holochain/holochain/actions/runs/12145561710)

**Review by matthme — APPROVED** [review]
Okay, should be ready now.

**Review by ThetaSinner — APPROVED** [review]

**Pull request merged**
