### PR TITLE
feat(nix): minimize rust toolchain size and test hc scaffold integration

### PR DESCRIPTION
**Pull request by steveej**
### TODO:
- [x] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by ThetaSinner — APPROVED** [review]
Looks awesome! Any idea on the real savings?

**Comment by ThetaSinner** [comment]
Also probably deserves a change log entry

**Review by jost-s — APPROVED** [review]

**Comment by ThetaSinner** [comment]
Update looks good, anything stopping this going in?

**Comment by steveej** [comment]
> Update looks good, anything stopping this going in?

CI tests have been failing, presumably due to the issue with a macos builder. now that it should be resolved let's see.

**Pull request merged**
