### PR TITLE
Fix up some problems for rust 1.68.0-nightly, so docs can be built

### PR DESCRIPTION
**Pull request by maackle**
### Summary

Just ran cargo check using latest nightly and fixed any errors and warnings.

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by matthme — APPROVED** [review]
This is way beyond my current level of Rust and Holochain core so I'll just trust you :)

**Comment by steveeJ** [comment]
we're running into issues because nightly has moved too far beyond the rust version we're using on CI. i have started work to bring it up to 1.64 and 1.66 but ran into a blocker because of a dependency. please find that work here: https://github.com/holochain/holochain/pull/1588

**Review by steveeJ — APPROVED** [review]
we're running into issues because nightly has moved too far beyond the rust version we're using on CI. i have started work to bring it up to 1.64 and 1.66 but ran into a blocker because of a dependency. please find that work here: https://github.com/holochain/holochain/pull/1588

i approve the changes here assuming we'll rebase it once rust 1.66 is the default

**Comment by neonphog** [comment]
Closing this as the changes were merged as part of https://github.com/holochain/holochain/pull/1735

**Pull request closed without merging**
