### PR TITLE
feat(github/release): skip entire test job on pull requests

### PR DESCRIPTION
**Pull request by steveeJ**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by jost-s — COMMENTED** [review]
Why should the tests be skipped on PRs?

**Comment by steveeJ** [comment]
> Why should the tests be skipped on PRs?

these are the release tests that are run in github actions. we currently run the CI tests in circleci.

**Comment by jost-s** [comment]
Ok, yeah.

**Comment by steveeJ** [comment]
they're also excluded via the matrix

https://github.com/holochain/holochain/blob/6d15dbc6cd552ee69fe585bcc1f83df1f9f1616c/.github/workflows/release.yml#L333-L335

but this lead to issues as github still tries to execute the matrix, however fails as it's empty.

**Review by jost-s — APPROVED** [review]

**Pull request merged**
