### PR TITLE
Bootstrap server

### PR DESCRIPTION
**Pull request by freesig**
Note this is currently only intended for testing and is not secure enough for production use.

### CODE REVIEW

**Comment by Connoropolous** [comment]
this is exciting. As I understand the existing bootstrap server can mostly (without changes) run on cloudflare. Will this become system agnostic, being written in Rust. It will need persistence beyond memory though I suspect, so how will you handle that?

**Comment by freesig** [comment]
@Connoropolous Yeh eventually it would be awesome use this outside testing. As you say we will need something beyond just memory. Perhaps something like Redis would be a good fit. Also we'd have to do a bit more work to make this secure.
If anyone has a need for non-cloudflare bootstrap sooner rather then later contributions are welcome :)

**Comment by Connoropolous** [comment]
what was the incentive to use this for testing exactly?

Redis sounds like a prime possibility, its very universal and low barrier solution

**Review by neonphog — APPROVED** [review]
Nice : )

I can expiration logic to this as part of the "leave" story so I can test that : )

**Comment by Connoropolous** [comment]
Nice. Will the expiration part also complete the security aspects of it, or thatd be separate?

**Comment by neonphog** [comment]
@Connoropolous 

> Nice. Will the expiration part also complete the security aspects of it, or thatd be separate?

For the moment, the bootstrap service is a totally open protocol, anyone with the address can publish an entry. We're basically not addressing security yet.

The plan on the Holo side is to introduce a kind of capability system where hApp devs can authorize trusted bootstrap nodes as our  first pass at security.

**Pull request merged**
