### PR TITLE
Switch default Holonix version to 0_2

### PR DESCRIPTION
**Pull request by ThetaSinner**
### Summary

When I ran `nix develop .#holonix` with this change it didn't do any rebuilding, so my best guess is that this won't have to update the cache. That's good!

I see the right versions of Holochain binaries and tools in the resulting shell.

### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by ThetaSinner** [comment]
We don't have to merge this right away, just getting it ready

**Comment by ThetaSinner** [comment]
Ideally we merge this first https://github.com/holochain/docs-pages/pull/426

**Review by jost-s — APPROVED** [review]
Approved anyway

**Review by steveej — APPROVED** [review]
to speed up cache population, we can trigger the [source update-dispatch](https://github.com/holochain/holochain/actions/workflows/update-dispatch.yml) immediately after merging this.

**Review by c12i — APPROVED** [review]

**Comment by ThetaSinner** [comment]
> to speed up cache population, we can trigger the [source update-dispatch](https://github.com/holochain/holochain/actions/workflows/update-dispatch.yml) immediately after merging this.

Per the PR description I don't think this is necessary. Nix didn't try to build anything for me locally and I have recent builds of 0.1 and 0.2 so that suggests to me that this will happily pull from the existing cache for 0.2

**Pull request merged**
