### PR TITLE
Update Cargo.toml

### PR DESCRIPTION
**Pull request by freesig**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by maackle** [comment]
What's this do? Speed up compilation?

**Comment by freesig** [comment]
Yeh but it seems to fail completely

**Comment by freesig** [comment]
@neonphog Why did we have the deps set to release builds anyway?

**Comment by neonphog** [comment]
> @neonphog Why did we have the deps set to release builds anyway?

@freesig wasmer needs to be built in release mode, otherwise it runs waaay slow

**Comment by freesig** [comment]
Is there a way to target just the wasmer dep?
Seems like CI runs an extra 10 mins faster?

**Comment by neonphog** [comment]
> Is there a way to target just the wasmer dep? Seems like CI runs an extra 10 mins faster?

@freesig yeah, there's that `."*"` in the toml header, I assume that has something to do with selection. You'd have to experiment though, I was just following instructions from a google search.

**Pull request closed without merging**
