### PR TITLE
Prepare for 0.2.2 release

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Comment by abe-njama** [comment]
I'd like to update the changelog to show all the changes that are part of this release. Can I do so in this PR @ThetaSinner ?

**Comment by ThetaSinner** [comment]
I'd prefer we not set a precedent for how that looks until we automate pulling `rc` changes forwards to the main release. Can the changes be included in the GitHub release notes like has been done previously?

**Comment by abe-njama** [comment]
Yeah, we can include the changes in the Github release notes as we've previously done. We'll proceed with that option with this release as well. Thanks.

**Review by abe-njama — APPROVED** [review]
LGTM

**Pull request merged**
