### PR TITLE
Clarify how to fix nix-shell unfree package issue

### PR DESCRIPTION
**Pull request by zdb999**
If you have a fresh install of Nix, `nix-shell` will fail to install ngrok and will error out. This adds instructions to the README for what to do when that happens.

### CODE REVIEW

**Comment by Connoropolous** [comment]
I encountered this issue too 👍

**Comment by Connoropolous** [comment]
this solution also just worked for me

**Review by maackle — APPROVED** [review]
Yep, this does the trick

**Comment by maackle** [comment]
I believe we're getting rid of `unfree` packages soon, right @thedavidmeister? I'll merge this for now though, since we haven't made that move yet.

**Pull request merged**
