### PR TITLE
Try to make trace capturing collisions less likely

### PR DESCRIPTION
**Pull request by maackle**
### Summary

Not foolproof, but will give other tests less time to seize the opportunity to add their own tracing to the global mutex

### TODO:
- [ ] ~~CHANGELOG(s) updated with appropriate info~~
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by freesig — CHANGES_REQUESTED** [review]
I don't think this a good solution. I think the test should just be deleted or we find a better way to fix it.

**Comment by maackle** [comment]
@freesig better than nothing though right? Can we either merge this or ignore that test?

**Comment by freesig** [comment]
@maackle It's already ignored on develop

**Comment by maackle** [comment]
@freesig oops yes sorry. Just figured, this can't hurt. And it still seems like a useful test to keep, which can be run by itself. Given that I'd still rather merge this than close it, unless you'd rather delete the test.

**Pull request closed without merging**
