### PR TITLE
Typo fix for element's docs: triple to tuple

### PR DESCRIPTION
**Pull request by the-a-man-006**
Found four instances of the word "triple" in element's doc-comments.
Corrected them to "tuple".

### CODE REVIEW

**Review by freesig — COMMENTED** [review]
This is a little weird because it kind of is a triple. `(Signature, Header, Entry)` except the `Signature` and `Header` are stored together. I could go either way on this.

**Comment by thedavidmeister** [comment]
@freesig i'm leaning more towards relating to it it as a tuple because it also is hashed, but that doesn't make it a quadruple :shrug:

actually i think it's just weird to be calling structs with fields any kind of "uple"

**Comment by the-a-man-006** [comment]
@thedavidmeister Should I literally make it a tuple then? I guess that wouldn't hurt?

**Comment by Connoropolous** [comment]
I had taken a quick look at this, and myself thought it's odd to call a struct a tuple, but you were just trying to make it better, and I think now you really have done. From my pov :)

**Comment by thedavidmeister** [comment]
sorry, i didn't mean my comment as a blocker, i was just kind of thinking out loud, i feel this is fine to merge like @Connoropolous said

**Review by thedavidmeister — APPROVED** [review]

**Review by thedavidmeister — CHANGES_REQUESTED** [review]
can we go back to having the element the way it was and just change the doc?

**Comment by the-a-man-006** [comment]
> a chain element containing the signed header along with the
> entry if the header type has one.

I think that should suffice. Both "tuple" and "triple" seem misleading, so did away with both.

**Review by thedavidmeister — APPROVED** [review]

**Comment by thedavidmeister** [comment]
lgtm

**Review by maackle — APPROVED** [review]
lgtm

**Pull request merged**
