### PR TITLE
Gossip all agents within the common arc set

### PR DESCRIPTION
**Pull request by freesig**
### INCLUDED CHANGES:
- Gossip all agents within the common arc set (even if empty).

### TODO:
- [x] CHANGELOG(s) updated with appropriate info

### CODE REVIEW

**Comment by maackle** [comment]
@alastairong do you remember if you cherry-picked this branch 2 years ago? This seems like a worthwhile fix at a glance.

**Comment by alastairong** [comment]
@maackle I can't say definitively but I'm fairly confident I did.

**Comment by maackle** [comment]
After reading this over I feel like we don't actually want to merge this:

This is mainly just including agents with empty arcs in gossip. However, we defined empty arcs to be non-participatory, i.e. they don't engage in gossip with anyone, and generally don't respond to requests. They only do gets. I don't know what the original intention was in including empty arcs in agent gossip, but I can't reconstruct it now.

@neonphog @artbrock any thoughts before I close this?

**Comment by alastairong** [comment]
@maackle 

In the past, the Holo context had hosted agents holding zero arcs but still being in active use. That is no longer the case. So perhaps this is now made obsolete by changes in context?

**Comment by maackle** [comment]
Thanks, that's helpful context. I think this had something to do with a workaround where only one local agent had a full arc, and all other local agents were given a zero arc?

@artbrock I know at one point you wanted agents' arcs to not be respected, so that all agents on a node are represented by a single arc that may or may not overlap their agent key's location. I don't think we fleshed that out. Either way, that's not currently implemented so I do think it's safe to let this PR wither away. Let's let stale-bot close this unless anyone objects.

**Pull request closed without merging**
