### PR TITLE
[0.1] pin serde better

### PR DESCRIPTION
**Pull request by ThetaSinner**
### TODO:
- [ ] CHANGELOG(s) updated with appropriate info
- [ ] Just before pressing the merge button, ensure new entries to CHANGELOG(s) are still under the _UNRELEASED_ heading

### CODE REVIEW

**Review by neonphog — APPROVED** [review]

**Comment by ThetaSinner** [comment]
Updated to use `>= 1.0, <= 1.0.166`

**Review by steveej — APPROVED** [review]
thanks!

**Comment by ThetaSinner** [comment]
This version has the problem with serde_derive pre-built binaries backed out -> https://github.com/serde-rs/serde/releases/tag/v1.0.184

Unpinning and upgrading to the latest version

**Comment by ThetaSinner** [comment]
Okay that doesn't work because of the other issue with serialisation differences on enums. This will have to stay pinned even though the latest version builds just fine

**Pull request merged**
